-- MebX_Qsys_Project_avalon_st_adapter_001.vhd

-- This file was auto-generated from altera_avalon_st_adapter_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 16.1 196

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MebX_Qsys_Project_avalon_st_adapter_001 is
	generic (
		inBitsPerSymbol : integer := 8;
		inUsePackets    : integer := 1;
		inDataWidth     : integer := 32;
		inChannelWidth  : integer := 0;
		inErrorWidth    : integer := 6;
		inUseEmptyPort  : integer := 1;
		inUseValid      : integer := 1;
		inUseReady      : integer := 1;
		inReadyLatency  : integer := 2;
		outDataWidth    : integer := 32;
		outChannelWidth : integer := 0;
		outErrorWidth   : integer := 0;
		outUseEmptyPort : integer := 1;
		outUseValid     : integer := 1;
		outUseReady     : integer := 1;
		outReadyLatency : integer := 0
	);
	port (
		in_clk_0_clk        : in  std_logic                     := '0';             -- in_clk_0.clk
		in_rst_0_reset      : in  std_logic                     := '0';             -- in_rst_0.reset
		in_0_data           : in  std_logic_vector(31 downto 0) := (others => '0'); --     in_0.data
		in_0_valid          : in  std_logic                     := '0';             --         .valid
		in_0_ready          : out std_logic;                                        --         .ready
		in_0_startofpacket  : in  std_logic                     := '0';             --         .startofpacket
		in_0_endofpacket    : in  std_logic                     := '0';             --         .endofpacket
		in_0_empty          : in  std_logic_vector(1 downto 0)  := (others => '0'); --         .empty
		in_0_error          : in  std_logic_vector(5 downto 0)  := (others => '0'); --         .error
		out_0_data          : out std_logic_vector(31 downto 0);                    --    out_0.data
		out_0_valid         : out std_logic;                                        --         .valid
		out_0_ready         : in  std_logic                     := '0';             --         .ready
		out_0_startofpacket : out std_logic;                                        --         .startofpacket
		out_0_endofpacket   : out std_logic;                                        --         .endofpacket
		out_0_empty         : out std_logic_vector(1 downto 0)                      --         .empty
	);
end entity MebX_Qsys_Project_avalon_st_adapter_001;

architecture rtl of MebX_Qsys_Project_avalon_st_adapter_001 is
	component MebX_Qsys_Project_avalon_st_adapter_001_error_adapter_0 is
		port (
			clk               : in  std_logic                     := 'X';             -- clk
			reset_n           : in  std_logic                     := 'X';             -- reset_n
			in_data           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data
			in_valid          : in  std_logic                     := 'X';             -- valid
			in_ready          : out std_logic;                                        -- ready
			in_startofpacket  : in  std_logic                     := 'X';             -- startofpacket
			in_endofpacket    : in  std_logic                     := 'X';             -- endofpacket
			in_empty          : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- empty
			in_error          : in  std_logic_vector(5 downto 0)  := (others => 'X'); -- error
			out_data          : out std_logic_vector(31 downto 0);                    -- data
			out_valid         : out std_logic;                                        -- valid
			out_ready         : in  std_logic                     := 'X';             -- ready
			out_startofpacket : out std_logic;                                        -- startofpacket
			out_endofpacket   : out std_logic;                                        -- endofpacket
			out_empty         : out std_logic_vector(1 downto 0)                      -- empty
		);
	end component MebX_Qsys_Project_avalon_st_adapter_001_error_adapter_0;

	component MebX_Qsys_Project_avalon_st_adapter_001_timing_adapter_0 is
		port (
			clk               : in  std_logic                     := 'X';             -- clk
			reset_n           : in  std_logic                     := 'X';             -- reset_n
			in_data           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data
			in_valid          : in  std_logic                     := 'X';             -- valid
			in_ready          : out std_logic;                                        -- ready
			in_startofpacket  : in  std_logic                     := 'X';             -- startofpacket
			in_endofpacket    : in  std_logic                     := 'X';             -- endofpacket
			in_empty          : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- empty
			out_data          : out std_logic_vector(31 downto 0);                    -- data
			out_valid         : out std_logic;                                        -- valid
			out_ready         : in  std_logic                     := 'X';             -- ready
			out_startofpacket : out std_logic;                                        -- startofpacket
			out_endofpacket   : out std_logic;                                        -- endofpacket
			out_empty         : out std_logic_vector(1 downto 0)                      -- empty
		);
	end component MebX_Qsys_Project_avalon_st_adapter_001_timing_adapter_0;

	signal error_adapter_0_out_valid         : std_logic;                     -- error_adapter_0:out_valid -> timing_adapter_0:in_valid
	signal error_adapter_0_out_data          : std_logic_vector(31 downto 0); -- error_adapter_0:out_data -> timing_adapter_0:in_data
	signal error_adapter_0_out_ready         : std_logic;                     -- timing_adapter_0:in_ready -> error_adapter_0:out_ready
	signal error_adapter_0_out_startofpacket : std_logic;                     -- error_adapter_0:out_startofpacket -> timing_adapter_0:in_startofpacket
	signal error_adapter_0_out_endofpacket   : std_logic;                     -- error_adapter_0:out_endofpacket -> timing_adapter_0:in_endofpacket
	signal error_adapter_0_out_empty         : std_logic_vector(1 downto 0);  -- error_adapter_0:out_empty -> timing_adapter_0:in_empty
	signal in_rst_0_reset_ports_inv          : std_logic;                     -- in_rst_0_reset:inv -> [error_adapter_0:reset_n, timing_adapter_0:reset_n]

begin

	inbitspersymbol_check : if inBitsPerSymbol /= 8 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inusepackets_check : if inUsePackets /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	indatawidth_check : if inDataWidth /= 32 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inchannelwidth_check : if inChannelWidth /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inerrorwidth_check : if inErrorWidth /= 6 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inuseemptyport_check : if inUseEmptyPort /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inusevalid_check : if inUseValid /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inuseready_check : if inUseReady /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inreadylatency_check : if inReadyLatency /= 2 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outdatawidth_check : if outDataWidth /= 32 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outchannelwidth_check : if outChannelWidth /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outerrorwidth_check : if outErrorWidth /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outuseemptyport_check : if outUseEmptyPort /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outusevalid_check : if outUseValid /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outuseready_check : if outUseReady /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outreadylatency_check : if outReadyLatency /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	error_adapter_0 : component MebX_Qsys_Project_avalon_st_adapter_001_error_adapter_0
		port map (
			clk               => in_clk_0_clk,                      --   clk.clk
			reset_n           => in_rst_0_reset_ports_inv,          -- reset.reset_n
			in_data           => in_0_data,                         --    in.data
			in_valid          => in_0_valid,                        --      .valid
			in_ready          => in_0_ready,                        --      .ready
			in_startofpacket  => in_0_startofpacket,                --      .startofpacket
			in_endofpacket    => in_0_endofpacket,                  --      .endofpacket
			in_empty          => in_0_empty,                        --      .empty
			in_error          => in_0_error,                        --      .error
			out_data          => error_adapter_0_out_data,          --   out.data
			out_valid         => error_adapter_0_out_valid,         --      .valid
			out_ready         => error_adapter_0_out_ready,         --      .ready
			out_startofpacket => error_adapter_0_out_startofpacket, --      .startofpacket
			out_endofpacket   => error_adapter_0_out_endofpacket,   --      .endofpacket
			out_empty         => error_adapter_0_out_empty          --      .empty
		);

	timing_adapter_0 : component MebX_Qsys_Project_avalon_st_adapter_001_timing_adapter_0
		port map (
			clk               => in_clk_0_clk,                      --   clk.clk
			reset_n           => in_rst_0_reset_ports_inv,          -- reset.reset_n
			in_data           => error_adapter_0_out_data,          --    in.data
			in_valid          => error_adapter_0_out_valid,         --      .valid
			in_ready          => error_adapter_0_out_ready,         --      .ready
			in_startofpacket  => error_adapter_0_out_startofpacket, --      .startofpacket
			in_endofpacket    => error_adapter_0_out_endofpacket,   --      .endofpacket
			in_empty          => error_adapter_0_out_empty,         --      .empty
			out_data          => out_0_data,                        --   out.data
			out_valid         => out_0_valid,                       --      .valid
			out_ready         => out_0_ready,                       --      .ready
			out_startofpacket => out_0_startofpacket,               --      .startofpacket
			out_endofpacket   => out_0_endofpacket,                 --      .endofpacket
			out_empty         => out_0_empty                        --      .empty
		);

	in_rst_0_reset_ports_inv <= not in_rst_0_reset;

end architecture rtl; -- of MebX_Qsys_Project_avalon_st_adapter_001
