/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'MebX_Qsys_Project'
 * SOPC Builder design path: ../../MebX_Qsys_Project.sopcinfo
 *
 * Generated: Tue May 04 09:36:30 BRT 2021
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x81218820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x20
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x81100020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 1
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 1
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_DIVISION_ERROR_EXCEPTION
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INST_ADDR_WIDTH 0x20
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x86020000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x81218820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x20
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x81100020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 1
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 1
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_DIVISION_ERROR_EXCEPTION
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INST_ADDR_WIDTH 0x20
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x86020000


/*
 * Communication_Module_v2_Ch1 configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_v2_Ch1 Communication_Module_v2
#define COMMUNICATION_MODULE_V2_CH1_BASE 0x8101dc00
#define COMMUNICATION_MODULE_V2_CH1_IRQ -1
#define COMMUNICATION_MODULE_V2_CH1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_V2_CH1_NAME "/dev/Communication_Module_v2_Ch1"
#define COMMUNICATION_MODULE_V2_CH1_SPAN 1024
#define COMMUNICATION_MODULE_V2_CH1_TYPE "Communication_Module_v2"


/*
 * Communication_Module_v2_Ch2 configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_v2_Ch2 Communication_Module_v2
#define COMMUNICATION_MODULE_V2_CH2_BASE 0x8101d800
#define COMMUNICATION_MODULE_V2_CH2_IRQ -1
#define COMMUNICATION_MODULE_V2_CH2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_V2_CH2_NAME "/dev/Communication_Module_v2_Ch2"
#define COMMUNICATION_MODULE_V2_CH2_SPAN 1024
#define COMMUNICATION_MODULE_V2_CH2_TYPE "Communication_Module_v2"


/*
 * Communication_Module_v2_Ch3 configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_v2_Ch3 Communication_Module_v2
#define COMMUNICATION_MODULE_V2_CH3_BASE 0x8101d400
#define COMMUNICATION_MODULE_V2_CH3_IRQ -1
#define COMMUNICATION_MODULE_V2_CH3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_V2_CH3_NAME "/dev/Communication_Module_v2_Ch3"
#define COMMUNICATION_MODULE_V2_CH3_SPAN 1024
#define COMMUNICATION_MODULE_V2_CH3_TYPE "Communication_Module_v2"


/*
 * Communication_Module_v2_Ch4 configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_v2_Ch4 Communication_Module_v2
#define COMMUNICATION_MODULE_V2_CH4_BASE 0x8101d000
#define COMMUNICATION_MODULE_V2_CH4_IRQ -1
#define COMMUNICATION_MODULE_V2_CH4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_V2_CH4_NAME "/dev/Communication_Module_v2_Ch4"
#define COMMUNICATION_MODULE_V2_CH4_SPAN 1024
#define COMMUNICATION_MODULE_V2_CH4_TYPE "Communication_Module_v2"


/*
 * Communication_Module_v2_Ch5 configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_v2_Ch5 Communication_Module_v2
#define COMMUNICATION_MODULE_V2_CH5_BASE 0x8101cc00
#define COMMUNICATION_MODULE_V2_CH5_IRQ -1
#define COMMUNICATION_MODULE_V2_CH5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_V2_CH5_NAME "/dev/Communication_Module_v2_Ch5"
#define COMMUNICATION_MODULE_V2_CH5_SPAN 1024
#define COMMUNICATION_MODULE_V2_CH5_TYPE "Communication_Module_v2"


/*
 * Communication_Module_v2_Ch6 configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_v2_Ch6 Communication_Module_v2
#define COMMUNICATION_MODULE_V2_CH6_BASE 0x8101c800
#define COMMUNICATION_MODULE_V2_CH6_IRQ -1
#define COMMUNICATION_MODULE_V2_CH6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_V2_CH6_NAME "/dev/Communication_Module_v2_Ch6"
#define COMMUNICATION_MODULE_V2_CH6_SPAN 1024
#define COMMUNICATION_MODULE_V2_CH6_TYPE "Communication_Module_v2"


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_ADDRESS_SPAN_EXTENDER
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_AVALON_UART
#define __ALTERA_GENERIC_TRISTATE_CONTROLLER
#define __ALTERA_NIOS2_GEN2
#define __COMMUNICATION_MODULE_V2
#define __FTDI_UMFT601A_MODULE
#define __MEMORY_FILLER
#define __RMAP_MEMORY_NFEE_AREA
#define __RMAP_MEMORY_SCOM_AREA
#define __RST_CONTROLLER
#define __SYNC
#define __SYNCHRONIZATION_COMM


/*
 * FTDI_UMFT601A_Module configuration
 *
 */

#define ALT_MODULE_CLASS_FTDI_UMFT601A_Module FTDI_UMFT601A_Module
#define FTDI_UMFT601A_MODULE_BASE 0x8101c400
#define FTDI_UMFT601A_MODULE_IRQ -1
#define FTDI_UMFT601A_MODULE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FTDI_UMFT601A_MODULE_NAME "/dev/FTDI_UMFT601A_Module"
#define FTDI_UMFT601A_MODULE_SPAN 1024
#define FTDI_UMFT601A_MODULE_TYPE "FTDI_UMFT601A_Module"


/*
 * Memory_Filler configuration
 *
 */

#define ALT_MODULE_CLASS_Memory_Filler Memory_Filler
#define MEMORY_FILLER_BASE 0x82000000
#define MEMORY_FILLER_IRQ -1
#define MEMORY_FILLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MEMORY_FILLER_NAME "/dev/Memory_Filler"
#define MEMORY_FILLER_SPAN 1024
#define MEMORY_FILLER_TYPE "Memory_Filler"


/*
 * Synchronization_COMM_0 configuration
 *
 */

#define ALT_MODULE_CLASS_Synchronization_COMM_0 Synchronization_COMM
#define SYNCHRONIZATION_COMM_0_BASE 0x8101c000
#define SYNCHRONIZATION_COMM_0_IRQ -1
#define SYNCHRONIZATION_COMM_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYNCHRONIZATION_COMM_0_NAME "/dev/Synchronization_COMM_0"
#define SYNCHRONIZATION_COMM_0_SPAN 1024
#define SYNCHRONIZATION_COMM_0_TYPE "Synchronization_COMM"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Stratix IV"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x8121af50
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/rs232_uart"
#define ALT_STDIN_BASE 0x80000840
#define ALT_STDIN_DEV rs232_uart
#define ALT_STDIN_IS_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_uart"
#define ALT_STDOUT "/dev/rs232_uart"
#define ALT_STDOUT_BASE 0x80000840
#define ALT_STDOUT_DEV rs232_uart
#define ALT_STDOUT_IS_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_uart"
#define ALT_SYSTEM_NAME "MebX_Qsys_Project"


/*
 * csense_adc_fo configuration
 *
 */

#define ALT_MODULE_CLASS_csense_adc_fo altera_avalon_pio
#define CSENSE_ADC_FO_BASE 0x80000910
#define CSENSE_ADC_FO_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_ADC_FO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_ADC_FO_CAPTURE 0
#define CSENSE_ADC_FO_DATA_WIDTH 1
#define CSENSE_ADC_FO_DO_TEST_BENCH_WIRING 0
#define CSENSE_ADC_FO_DRIVEN_SIM_VALUE 0
#define CSENSE_ADC_FO_EDGE_TYPE "NONE"
#define CSENSE_ADC_FO_FREQ 50000000
#define CSENSE_ADC_FO_HAS_IN 0
#define CSENSE_ADC_FO_HAS_OUT 1
#define CSENSE_ADC_FO_HAS_TRI 0
#define CSENSE_ADC_FO_IRQ -1
#define CSENSE_ADC_FO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_ADC_FO_IRQ_TYPE "NONE"
#define CSENSE_ADC_FO_NAME "/dev/csense_adc_fo"
#define CSENSE_ADC_FO_RESET_VALUE 0
#define CSENSE_ADC_FO_SPAN 16
#define CSENSE_ADC_FO_TYPE "altera_avalon_pio"


/*
 * csense_cs_n configuration
 *
 */

#define ALT_MODULE_CLASS_csense_cs_n altera_avalon_pio
#define CSENSE_CS_N_BASE 0x80000920
#define CSENSE_CS_N_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_CS_N_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_CS_N_CAPTURE 0
#define CSENSE_CS_N_DATA_WIDTH 2
#define CSENSE_CS_N_DO_TEST_BENCH_WIRING 0
#define CSENSE_CS_N_DRIVEN_SIM_VALUE 0
#define CSENSE_CS_N_EDGE_TYPE "NONE"
#define CSENSE_CS_N_FREQ 50000000
#define CSENSE_CS_N_HAS_IN 0
#define CSENSE_CS_N_HAS_OUT 1
#define CSENSE_CS_N_HAS_TRI 0
#define CSENSE_CS_N_IRQ -1
#define CSENSE_CS_N_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_CS_N_IRQ_TYPE "NONE"
#define CSENSE_CS_N_NAME "/dev/csense_cs_n"
#define CSENSE_CS_N_RESET_VALUE 0
#define CSENSE_CS_N_SPAN 16
#define CSENSE_CS_N_TYPE "altera_avalon_pio"


/*
 * csense_sck configuration
 *
 */

#define ALT_MODULE_CLASS_csense_sck altera_avalon_pio
#define CSENSE_SCK_BASE 0x80000930
#define CSENSE_SCK_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_SCK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_SCK_CAPTURE 0
#define CSENSE_SCK_DATA_WIDTH 1
#define CSENSE_SCK_DO_TEST_BENCH_WIRING 0
#define CSENSE_SCK_DRIVEN_SIM_VALUE 0
#define CSENSE_SCK_EDGE_TYPE "NONE"
#define CSENSE_SCK_FREQ 50000000
#define CSENSE_SCK_HAS_IN 0
#define CSENSE_SCK_HAS_OUT 1
#define CSENSE_SCK_HAS_TRI 0
#define CSENSE_SCK_IRQ -1
#define CSENSE_SCK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_SCK_IRQ_TYPE "NONE"
#define CSENSE_SCK_NAME "/dev/csense_sck"
#define CSENSE_SCK_RESET_VALUE 0
#define CSENSE_SCK_SPAN 16
#define CSENSE_SCK_TYPE "altera_avalon_pio"


/*
 * csense_sdi configuration
 *
 */

#define ALT_MODULE_CLASS_csense_sdi altera_avalon_pio
#define CSENSE_SDI_BASE 0x80000940
#define CSENSE_SDI_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_SDI_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_SDI_CAPTURE 0
#define CSENSE_SDI_DATA_WIDTH 1
#define CSENSE_SDI_DO_TEST_BENCH_WIRING 0
#define CSENSE_SDI_DRIVEN_SIM_VALUE 0
#define CSENSE_SDI_EDGE_TYPE "NONE"
#define CSENSE_SDI_FREQ 50000000
#define CSENSE_SDI_HAS_IN 0
#define CSENSE_SDI_HAS_OUT 1
#define CSENSE_SDI_HAS_TRI 0
#define CSENSE_SDI_IRQ -1
#define CSENSE_SDI_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_SDI_IRQ_TYPE "NONE"
#define CSENSE_SDI_NAME "/dev/csense_sdi"
#define CSENSE_SDI_RESET_VALUE 0
#define CSENSE_SDI_SPAN 16
#define CSENSE_SDI_TYPE "altera_avalon_pio"


/*
 * csense_sdo configuration
 *
 */

#define ALT_MODULE_CLASS_csense_sdo altera_avalon_pio
#define CSENSE_SDO_BASE 0x80000950
#define CSENSE_SDO_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_SDO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_SDO_CAPTURE 0
#define CSENSE_SDO_DATA_WIDTH 1
#define CSENSE_SDO_DO_TEST_BENCH_WIRING 0
#define CSENSE_SDO_DRIVEN_SIM_VALUE 0
#define CSENSE_SDO_EDGE_TYPE "NONE"
#define CSENSE_SDO_FREQ 50000000
#define CSENSE_SDO_HAS_IN 1
#define CSENSE_SDO_HAS_OUT 0
#define CSENSE_SDO_HAS_TRI 0
#define CSENSE_SDO_IRQ -1
#define CSENSE_SDO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_SDO_IRQ_TYPE "NONE"
#define CSENSE_SDO_NAME "/dev/csense_sdo"
#define CSENSE_SDO_RESET_VALUE 0
#define CSENSE_SDO_SPAN 16
#define CSENSE_SDO_TYPE "altera_avalon_pio"


/*
 * ddr2_address_span_extender_cntl configuration
 *
 */

#define ALT_MODULE_CLASS_ddr2_address_span_extender_cntl altera_address_span_extender
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_BASE 0x8101e000
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_BURSTCOUNT_WIDTH 8
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_BYTEENABLE_WIDTH 4
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_CNTL_ADDRESS_WIDTH 1
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_DATA_WIDTH 32
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_IRQ -1
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_MASTER_ADDRESS_WIDTH 0x20
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_MAX_BURST_BYTES 512
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_MAX_BURST_WORDS 128
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_NAME "/dev/ddr2_address_span_extender_cntl"
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_SLAVE_ADDRESS_SHIFT 0x2
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_SLAVE_ADDRESS_WIDTH 0x1d
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_SPAN 8
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_SUB_WINDOW_COUNT 1
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_TYPE "altera_address_span_extender"


/*
 * ddr2_address_span_extender_windowed_slave configuration
 *
 */

#define ALT_MODULE_CLASS_ddr2_address_span_extender_windowed_slave altera_address_span_extender
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_BASE 0x0
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_BURSTCOUNT_WIDTH 8
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_BYTEENABLE_WIDTH 4
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_CNTL_ADDRESS_WIDTH 1
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_DATA_WIDTH 32
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_IRQ -1
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_MASTER_ADDRESS_WIDTH 0x20
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_MAX_BURST_BYTES 512
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_MAX_BURST_WORDS 128
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_NAME "/dev/ddr2_address_span_extender_windowed_slave"
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_SLAVE_ADDRESS_SHIFT 0x2
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_SLAVE_ADDRESS_WIDTH 0x1d
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_SPAN 2147483648
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_SUB_WINDOW_COUNT 1
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_TYPE "altera_address_span_extender"


/*
 * ext_flash configuration
 *
 */

#define ALT_MODULE_CLASS_ext_flash altera_generic_tristate_controller
#define EXT_FLASH_BASE 0x84000000
#define EXT_FLASH_HOLD_VALUE 20
#define EXT_FLASH_IRQ -1
#define EXT_FLASH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXT_FLASH_NAME "/dev/ext_flash"
#define EXT_FLASH_SETUP_VALUE 25
#define EXT_FLASH_SIZE 33554432u
#define EXT_FLASH_SPAN 67108864
#define EXT_FLASH_TIMING_UNITS "ns"
#define EXT_FLASH_TYPE "altera_generic_tristate_controller"
#define EXT_FLASH_WAIT_VALUE 100


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER_1MS
#define ALT_TIMESTAMP_CLK TIMER_1MS


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x8121af50
#define JTAG_UART_0_IRQ 14
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * m1_ddr2_i2c_scl configuration
 *
 */

#define ALT_MODULE_CLASS_m1_ddr2_i2c_scl altera_avalon_pio
#define M1_DDR2_I2C_SCL_BASE 0x800009f0
#define M1_DDR2_I2C_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define M1_DDR2_I2C_SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define M1_DDR2_I2C_SCL_CAPTURE 0
#define M1_DDR2_I2C_SCL_DATA_WIDTH 1
#define M1_DDR2_I2C_SCL_DO_TEST_BENCH_WIRING 0
#define M1_DDR2_I2C_SCL_DRIVEN_SIM_VALUE 0
#define M1_DDR2_I2C_SCL_EDGE_TYPE "NONE"
#define M1_DDR2_I2C_SCL_FREQ 50000000
#define M1_DDR2_I2C_SCL_HAS_IN 0
#define M1_DDR2_I2C_SCL_HAS_OUT 1
#define M1_DDR2_I2C_SCL_HAS_TRI 0
#define M1_DDR2_I2C_SCL_IRQ -1
#define M1_DDR2_I2C_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define M1_DDR2_I2C_SCL_IRQ_TYPE "NONE"
#define M1_DDR2_I2C_SCL_NAME "/dev/m1_ddr2_i2c_scl"
#define M1_DDR2_I2C_SCL_RESET_VALUE 0
#define M1_DDR2_I2C_SCL_SPAN 16
#define M1_DDR2_I2C_SCL_TYPE "altera_avalon_pio"


/*
 * m1_ddr2_i2c_sda configuration
 *
 */

#define ALT_MODULE_CLASS_m1_ddr2_i2c_sda altera_avalon_pio
#define M1_DDR2_I2C_SDA_BASE 0x80000a00
#define M1_DDR2_I2C_SDA_BIT_CLEARING_EDGE_REGISTER 0
#define M1_DDR2_I2C_SDA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define M1_DDR2_I2C_SDA_CAPTURE 0
#define M1_DDR2_I2C_SDA_DATA_WIDTH 1
#define M1_DDR2_I2C_SDA_DO_TEST_BENCH_WIRING 0
#define M1_DDR2_I2C_SDA_DRIVEN_SIM_VALUE 0
#define M1_DDR2_I2C_SDA_EDGE_TYPE "NONE"
#define M1_DDR2_I2C_SDA_FREQ 50000000
#define M1_DDR2_I2C_SDA_HAS_IN 0
#define M1_DDR2_I2C_SDA_HAS_OUT 0
#define M1_DDR2_I2C_SDA_HAS_TRI 1
#define M1_DDR2_I2C_SDA_IRQ -1
#define M1_DDR2_I2C_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define M1_DDR2_I2C_SDA_IRQ_TYPE "NONE"
#define M1_DDR2_I2C_SDA_NAME "/dev/m1_ddr2_i2c_sda"
#define M1_DDR2_I2C_SDA_RESET_VALUE 0
#define M1_DDR2_I2C_SDA_SPAN 16
#define M1_DDR2_I2C_SDA_TYPE "altera_avalon_pio"


/*
 * m2_ddr2_i2c_scl configuration
 *
 */

#define ALT_MODULE_CLASS_m2_ddr2_i2c_scl altera_avalon_pio
#define M2_DDR2_I2C_SCL_BASE 0x80000960
#define M2_DDR2_I2C_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define M2_DDR2_I2C_SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define M2_DDR2_I2C_SCL_CAPTURE 0
#define M2_DDR2_I2C_SCL_DATA_WIDTH 1
#define M2_DDR2_I2C_SCL_DO_TEST_BENCH_WIRING 0
#define M2_DDR2_I2C_SCL_DRIVEN_SIM_VALUE 0
#define M2_DDR2_I2C_SCL_EDGE_TYPE "NONE"
#define M2_DDR2_I2C_SCL_FREQ 50000000
#define M2_DDR2_I2C_SCL_HAS_IN 0
#define M2_DDR2_I2C_SCL_HAS_OUT 1
#define M2_DDR2_I2C_SCL_HAS_TRI 0
#define M2_DDR2_I2C_SCL_IRQ -1
#define M2_DDR2_I2C_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define M2_DDR2_I2C_SCL_IRQ_TYPE "NONE"
#define M2_DDR2_I2C_SCL_NAME "/dev/m2_ddr2_i2c_scl"
#define M2_DDR2_I2C_SCL_RESET_VALUE 0
#define M2_DDR2_I2C_SCL_SPAN 16
#define M2_DDR2_I2C_SCL_TYPE "altera_avalon_pio"


/*
 * m2_ddr2_i2c_sda configuration
 *
 */

#define ALT_MODULE_CLASS_m2_ddr2_i2c_sda altera_avalon_pio
#define M2_DDR2_I2C_SDA_BASE 0x80000970
#define M2_DDR2_I2C_SDA_BIT_CLEARING_EDGE_REGISTER 0
#define M2_DDR2_I2C_SDA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define M2_DDR2_I2C_SDA_CAPTURE 0
#define M2_DDR2_I2C_SDA_DATA_WIDTH 1
#define M2_DDR2_I2C_SDA_DO_TEST_BENCH_WIRING 0
#define M2_DDR2_I2C_SDA_DRIVEN_SIM_VALUE 0
#define M2_DDR2_I2C_SDA_EDGE_TYPE "NONE"
#define M2_DDR2_I2C_SDA_FREQ 50000000
#define M2_DDR2_I2C_SDA_HAS_IN 0
#define M2_DDR2_I2C_SDA_HAS_OUT 0
#define M2_DDR2_I2C_SDA_HAS_TRI 1
#define M2_DDR2_I2C_SDA_IRQ -1
#define M2_DDR2_I2C_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define M2_DDR2_I2C_SDA_IRQ_TYPE "NONE"
#define M2_DDR2_I2C_SDA_NAME "/dev/m2_ddr2_i2c_sda"
#define M2_DDR2_I2C_SDA_RESET_VALUE 0
#define M2_DDR2_I2C_SDA_SPAN 16
#define M2_DDR2_I2C_SDA_TYPE "altera_avalon_pio"


/*
 * onchip_memory configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_BASE 0x81100000
#define ONCHIP_MEMORY_CONTENTS_INFO ""
#define ONCHIP_MEMORY_DUAL_PORT 0
#define ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE "M9K"
#define ONCHIP_MEMORY_INIT_CONTENTS_FILE "MebX_Qsys_Project_onchip_memory"
#define ONCHIP_MEMORY_INIT_MEM_CONTENT 0
#define ONCHIP_MEMORY_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY_IRQ -1
#define ONCHIP_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY_NAME "/dev/onchip_memory"
#define ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_RAM_BLOCK_TYPE "M9K"
#define ONCHIP_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_SIZE_VALUE 786432
#define ONCHIP_MEMORY_SPAN 786432
#define ONCHIP_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY_WRITABLE 1


/*
 * pio_BUTTON configuration
 *
 */

#define ALT_MODULE_CLASS_pio_BUTTON altera_avalon_pio
#define PIO_BUTTON_BASE 0x800009e0
#define PIO_BUTTON_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_BUTTON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_BUTTON_CAPTURE 0
#define PIO_BUTTON_DATA_WIDTH 4
#define PIO_BUTTON_DO_TEST_BENCH_WIRING 0
#define PIO_BUTTON_DRIVEN_SIM_VALUE 0
#define PIO_BUTTON_EDGE_TYPE "NONE"
#define PIO_BUTTON_FREQ 50000000
#define PIO_BUTTON_HAS_IN 1
#define PIO_BUTTON_HAS_OUT 0
#define PIO_BUTTON_HAS_TRI 0
#define PIO_BUTTON_IRQ -1
#define PIO_BUTTON_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_BUTTON_IRQ_TYPE "NONE"
#define PIO_BUTTON_NAME "/dev/pio_BUTTON"
#define PIO_BUTTON_RESET_VALUE 0
#define PIO_BUTTON_SPAN 16
#define PIO_BUTTON_TYPE "altera_avalon_pio"


/*
 * pio_DIP configuration
 *
 */

#define ALT_MODULE_CLASS_pio_DIP altera_avalon_pio
#define PIO_DIP_BASE 0x800009c0
#define PIO_DIP_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_DIP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_DIP_CAPTURE 0
#define PIO_DIP_DATA_WIDTH 8
#define PIO_DIP_DO_TEST_BENCH_WIRING 0
#define PIO_DIP_DRIVEN_SIM_VALUE 0
#define PIO_DIP_EDGE_TYPE "NONE"
#define PIO_DIP_FREQ 50000000
#define PIO_DIP_HAS_IN 1
#define PIO_DIP_HAS_OUT 0
#define PIO_DIP_HAS_TRI 0
#define PIO_DIP_IRQ -1
#define PIO_DIP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_DIP_IRQ_TYPE "NONE"
#define PIO_DIP_NAME "/dev/pio_DIP"
#define PIO_DIP_RESET_VALUE 0
#define PIO_DIP_SPAN 16
#define PIO_DIP_TYPE "altera_avalon_pio"


/*
 * pio_EXT configuration
 *
 */

#define ALT_MODULE_CLASS_pio_EXT altera_avalon_pio
#define PIO_EXT_BASE 0x800009b0
#define PIO_EXT_BIT_CLEARING_EDGE_REGISTER 1
#define PIO_EXT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_EXT_CAPTURE 0
#define PIO_EXT_DATA_WIDTH 1
#define PIO_EXT_DO_TEST_BENCH_WIRING 0
#define PIO_EXT_DRIVEN_SIM_VALUE 0
#define PIO_EXT_EDGE_TYPE "NONE"
#define PIO_EXT_FREQ 50000000
#define PIO_EXT_HAS_IN 1
#define PIO_EXT_HAS_OUT 0
#define PIO_EXT_HAS_TRI 0
#define PIO_EXT_IRQ -1
#define PIO_EXT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_EXT_IRQ_TYPE "NONE"
#define PIO_EXT_NAME "/dev/pio_EXT"
#define PIO_EXT_RESET_VALUE 0
#define PIO_EXT_SPAN 16
#define PIO_EXT_TYPE "altera_avalon_pio"


/*
 * pio_LED configuration
 *
 */

#define ALT_MODULE_CLASS_pio_LED altera_avalon_pio
#define PIO_LED_BASE 0x800009d0
#define PIO_LED_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LED_CAPTURE 0
#define PIO_LED_DATA_WIDTH 8
#define PIO_LED_DO_TEST_BENCH_WIRING 0
#define PIO_LED_DRIVEN_SIM_VALUE 0
#define PIO_LED_EDGE_TYPE "NONE"
#define PIO_LED_FREQ 50000000
#define PIO_LED_HAS_IN 0
#define PIO_LED_HAS_OUT 1
#define PIO_LED_HAS_TRI 0
#define PIO_LED_IRQ -1
#define PIO_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_LED_IRQ_TYPE "NONE"
#define PIO_LED_NAME "/dev/pio_LED"
#define PIO_LED_RESET_VALUE 0
#define PIO_LED_SPAN 16
#define PIO_LED_TYPE "altera_avalon_pio"


/*
 * pio_LED_painel configuration
 *
 */

#define ALT_MODULE_CLASS_pio_LED_painel altera_avalon_pio
#define PIO_LED_PAINEL_BASE 0x80000900
#define PIO_LED_PAINEL_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_PAINEL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LED_PAINEL_CAPTURE 0
#define PIO_LED_PAINEL_DATA_WIDTH 21
#define PIO_LED_PAINEL_DO_TEST_BENCH_WIRING 0
#define PIO_LED_PAINEL_DRIVEN_SIM_VALUE 0
#define PIO_LED_PAINEL_EDGE_TYPE "NONE"
#define PIO_LED_PAINEL_FREQ 50000000
#define PIO_LED_PAINEL_HAS_IN 0
#define PIO_LED_PAINEL_HAS_OUT 1
#define PIO_LED_PAINEL_HAS_TRI 0
#define PIO_LED_PAINEL_IRQ -1
#define PIO_LED_PAINEL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_LED_PAINEL_IRQ_TYPE "NONE"
#define PIO_LED_PAINEL_NAME "/dev/pio_LED_painel"
#define PIO_LED_PAINEL_RESET_VALUE 65536
#define PIO_LED_PAINEL_SPAN 16
#define PIO_LED_PAINEL_TYPE "altera_avalon_pio"


/*
 * pio_ctrl_io_lvds configuration
 *
 */

#define ALT_MODULE_CLASS_pio_ctrl_io_lvds altera_avalon_pio
#define PIO_CTRL_IO_LVDS_BASE 0x800008a0
#define PIO_CTRL_IO_LVDS_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_CTRL_IO_LVDS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_CTRL_IO_LVDS_CAPTURE 0
#define PIO_CTRL_IO_LVDS_DATA_WIDTH 4
#define PIO_CTRL_IO_LVDS_DO_TEST_BENCH_WIRING 0
#define PIO_CTRL_IO_LVDS_DRIVEN_SIM_VALUE 0
#define PIO_CTRL_IO_LVDS_EDGE_TYPE "NONE"
#define PIO_CTRL_IO_LVDS_FREQ 50000000
#define PIO_CTRL_IO_LVDS_HAS_IN 0
#define PIO_CTRL_IO_LVDS_HAS_OUT 1
#define PIO_CTRL_IO_LVDS_HAS_TRI 0
#define PIO_CTRL_IO_LVDS_IRQ -1
#define PIO_CTRL_IO_LVDS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_CTRL_IO_LVDS_IRQ_TYPE "NONE"
#define PIO_CTRL_IO_LVDS_NAME "/dev/pio_ctrl_io_lvds"
#define PIO_CTRL_IO_LVDS_RESET_VALUE 4
#define PIO_CTRL_IO_LVDS_SPAN 16
#define PIO_CTRL_IO_LVDS_TYPE "altera_avalon_pio"


/*
 * rmap_mem_nfee_comm_1 configuration
 *
 */

#define ALT_MODULE_CLASS_rmap_mem_nfee_comm_1 RMAP_Memory_NFEE_Area
#define RMAP_MEM_NFEE_COMM_1_BASE 0x81018000
#define RMAP_MEM_NFEE_COMM_1_IRQ -1
#define RMAP_MEM_NFEE_COMM_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RMAP_MEM_NFEE_COMM_1_NAME "/dev/rmap_mem_nfee_comm_1"
#define RMAP_MEM_NFEE_COMM_1_SPAN 16384
#define RMAP_MEM_NFEE_COMM_1_TYPE "RMAP_Memory_NFEE_Area"


/*
 * rmap_mem_nfee_comm_2 configuration
 *
 */

#define ALT_MODULE_CLASS_rmap_mem_nfee_comm_2 RMAP_Memory_NFEE_Area
#define RMAP_MEM_NFEE_COMM_2_BASE 0x81014000
#define RMAP_MEM_NFEE_COMM_2_IRQ -1
#define RMAP_MEM_NFEE_COMM_2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RMAP_MEM_NFEE_COMM_2_NAME "/dev/rmap_mem_nfee_comm_2"
#define RMAP_MEM_NFEE_COMM_2_SPAN 16384
#define RMAP_MEM_NFEE_COMM_2_TYPE "RMAP_Memory_NFEE_Area"


/*
 * rmap_mem_nfee_comm_3 configuration
 *
 */

#define ALT_MODULE_CLASS_rmap_mem_nfee_comm_3 RMAP_Memory_NFEE_Area
#define RMAP_MEM_NFEE_COMM_3_BASE 0x81010000
#define RMAP_MEM_NFEE_COMM_3_IRQ -1
#define RMAP_MEM_NFEE_COMM_3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RMAP_MEM_NFEE_COMM_3_NAME "/dev/rmap_mem_nfee_comm_3"
#define RMAP_MEM_NFEE_COMM_3_SPAN 16384
#define RMAP_MEM_NFEE_COMM_3_TYPE "RMAP_Memory_NFEE_Area"


/*
 * rmap_mem_nfee_comm_4 configuration
 *
 */

#define ALT_MODULE_CLASS_rmap_mem_nfee_comm_4 RMAP_Memory_NFEE_Area
#define RMAP_MEM_NFEE_COMM_4_BASE 0x8100c000
#define RMAP_MEM_NFEE_COMM_4_IRQ -1
#define RMAP_MEM_NFEE_COMM_4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RMAP_MEM_NFEE_COMM_4_NAME "/dev/rmap_mem_nfee_comm_4"
#define RMAP_MEM_NFEE_COMM_4_SPAN 16384
#define RMAP_MEM_NFEE_COMM_4_TYPE "RMAP_Memory_NFEE_Area"


/*
 * rmap_mem_nfee_comm_5 configuration
 *
 */

#define ALT_MODULE_CLASS_rmap_mem_nfee_comm_5 RMAP_Memory_NFEE_Area
#define RMAP_MEM_NFEE_COMM_5_BASE 0x81008000
#define RMAP_MEM_NFEE_COMM_5_IRQ -1
#define RMAP_MEM_NFEE_COMM_5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RMAP_MEM_NFEE_COMM_5_NAME "/dev/rmap_mem_nfee_comm_5"
#define RMAP_MEM_NFEE_COMM_5_SPAN 16384
#define RMAP_MEM_NFEE_COMM_5_TYPE "RMAP_Memory_NFEE_Area"


/*
 * rmap_mem_nfee_comm_6 configuration
 *
 */

#define ALT_MODULE_CLASS_rmap_mem_nfee_comm_6 RMAP_Memory_NFEE_Area
#define RMAP_MEM_NFEE_COMM_6_BASE 0x81004000
#define RMAP_MEM_NFEE_COMM_6_IRQ -1
#define RMAP_MEM_NFEE_COMM_6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RMAP_MEM_NFEE_COMM_6_NAME "/dev/rmap_mem_nfee_comm_6"
#define RMAP_MEM_NFEE_COMM_6_SPAN 16384
#define RMAP_MEM_NFEE_COMM_6_TYPE "RMAP_Memory_NFEE_Area"


/*
 * rmap_mem_nfee_scom_0 configuration
 *
 */

#define ALT_MODULE_CLASS_rmap_mem_nfee_scom_0 RMAP_Memory_SCOM_Area
#define RMAP_MEM_NFEE_SCOM_0_BASE 0x81000000
#define RMAP_MEM_NFEE_SCOM_0_IRQ -1
#define RMAP_MEM_NFEE_SCOM_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RMAP_MEM_NFEE_SCOM_0_NAME "/dev/rmap_mem_nfee_scom_0"
#define RMAP_MEM_NFEE_SCOM_0_SPAN 16384
#define RMAP_MEM_NFEE_SCOM_0_TYPE "RMAP_Memory_SCOM_Area"


/*
 * rs232_uart configuration
 *
 */

#define ALT_MODULE_CLASS_rs232_uart altera_avalon_uart
#define RS232_UART_BASE 0x80000840
#define RS232_UART_BAUD 115200
#define RS232_UART_DATA_BITS 8
#define RS232_UART_FIXED_BAUD 0
#define RS232_UART_FREQ 50000000
#define RS232_UART_IRQ 13
#define RS232_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define RS232_UART_NAME "/dev/rs232_uart"
#define RS232_UART_PARITY 'N'
#define RS232_UART_SIM_CHAR_STREAM ""
#define RS232_UART_SIM_TRUE_BAUD 0
#define RS232_UART_SPAN 32
#define RS232_UART_STOP_BITS 1
#define RS232_UART_SYNC_REG_DEPTH 2
#define RS232_UART_TYPE "altera_avalon_uart"
#define RS232_UART_USE_CTS_RTS 0
#define RS232_UART_USE_EOP_REGISTER 0


/*
 * rst_controller configuration
 *
 */

#define ALT_MODULE_CLASS_rst_controller rst_controller
#define RST_CONTROLLER_BASE 0x80000800
#define RST_CONTROLLER_IRQ -1
#define RST_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RST_CONTROLLER_NAME "/dev/rst_controller"
#define RST_CONTROLLER_SPAN 64
#define RST_CONTROLLER_TYPE "rst_controller"


/*
 * sd_card_wp_n configuration
 *
 */

#define ALT_MODULE_CLASS_sd_card_wp_n altera_avalon_pio
#define SD_CARD_WP_N_BASE 0x800009a0
#define SD_CARD_WP_N_BIT_CLEARING_EDGE_REGISTER 0
#define SD_CARD_WP_N_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SD_CARD_WP_N_CAPTURE 0
#define SD_CARD_WP_N_DATA_WIDTH 1
#define SD_CARD_WP_N_DO_TEST_BENCH_WIRING 0
#define SD_CARD_WP_N_DRIVEN_SIM_VALUE 0
#define SD_CARD_WP_N_EDGE_TYPE "NONE"
#define SD_CARD_WP_N_FREQ 50000000
#define SD_CARD_WP_N_HAS_IN 1
#define SD_CARD_WP_N_HAS_OUT 0
#define SD_CARD_WP_N_HAS_TRI 0
#define SD_CARD_WP_N_IRQ -1
#define SD_CARD_WP_N_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SD_CARD_WP_N_IRQ_TYPE "NONE"
#define SD_CARD_WP_N_NAME "/dev/sd_card_wp_n"
#define SD_CARD_WP_N_RESET_VALUE 0
#define SD_CARD_WP_N_SPAN 16
#define SD_CARD_WP_N_TYPE "altera_avalon_pio"


/*
 * sync configuration
 *
 */

#define ALT_MODULE_CLASS_sync Sync
#define SYNC_BASE 0x80000400
#define SYNC_IRQ -1
#define SYNC_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYNC_NAME "/dev/sync"
#define SYNC_SPAN 1024
#define SYNC_TYPE "Sync"


/*
 * sysid_qsys configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys altera_avalon_sysid_qsys
#define SYSID_QSYS_BASE 0x8121af40
#define SYSID_QSYS_ID 113
#define SYSID_QSYS_IRQ -1
#define SYSID_QSYS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_NAME "/dev/sysid_qsys"
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_TIMESTAMP 1620091892
#define SYSID_QSYS_TYPE "altera_avalon_sysid_qsys"


/*
 * temp_scl configuration
 *
 */

#define ALT_MODULE_CLASS_temp_scl altera_avalon_pio
#define TEMP_SCL_BASE 0x80000990
#define TEMP_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP_SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP_SCL_CAPTURE 0
#define TEMP_SCL_DATA_WIDTH 1
#define TEMP_SCL_DO_TEST_BENCH_WIRING 0
#define TEMP_SCL_DRIVEN_SIM_VALUE 0
#define TEMP_SCL_EDGE_TYPE "NONE"
#define TEMP_SCL_FREQ 50000000
#define TEMP_SCL_HAS_IN 0
#define TEMP_SCL_HAS_OUT 1
#define TEMP_SCL_HAS_TRI 0
#define TEMP_SCL_IRQ -1
#define TEMP_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TEMP_SCL_IRQ_TYPE "NONE"
#define TEMP_SCL_NAME "/dev/temp_scl"
#define TEMP_SCL_RESET_VALUE 0
#define TEMP_SCL_SPAN 16
#define TEMP_SCL_TYPE "altera_avalon_pio"


/*
 * temp_sda configuration
 *
 */

#define ALT_MODULE_CLASS_temp_sda altera_avalon_pio
#define TEMP_SDA_BASE 0x80000980
#define TEMP_SDA_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP_SDA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP_SDA_CAPTURE 0
#define TEMP_SDA_DATA_WIDTH 1
#define TEMP_SDA_DO_TEST_BENCH_WIRING 0
#define TEMP_SDA_DRIVEN_SIM_VALUE 0
#define TEMP_SDA_EDGE_TYPE "NONE"
#define TEMP_SDA_FREQ 50000000
#define TEMP_SDA_HAS_IN 0
#define TEMP_SDA_HAS_OUT 0
#define TEMP_SDA_HAS_TRI 1
#define TEMP_SDA_IRQ -1
#define TEMP_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TEMP_SDA_IRQ_TYPE "NONE"
#define TEMP_SDA_NAME "/dev/temp_sda"
#define TEMP_SDA_RESET_VALUE 0
#define TEMP_SDA_SPAN 16
#define TEMP_SDA_TYPE "altera_avalon_pio"


/*
 * timer_1ms configuration
 *
 */

#define ALT_MODULE_CLASS_timer_1ms altera_avalon_timer
#define TIMER_1MS_ALWAYS_RUN 1
#define TIMER_1MS_BASE 0x80000880
#define TIMER_1MS_COUNTER_SIZE 32
#define TIMER_1MS_FIXED_PERIOD 0
#define TIMER_1MS_FREQ 50000000
#define TIMER_1MS_IRQ 0
#define TIMER_1MS_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_1MS_LOAD_VALUE 49999
#define TIMER_1MS_MULT 0.001
#define TIMER_1MS_NAME "/dev/timer_1ms"
#define TIMER_1MS_PERIOD 1
#define TIMER_1MS_PERIOD_UNITS "ms"
#define TIMER_1MS_RESET_OUTPUT 0
#define TIMER_1MS_SNAPSHOT 1
#define TIMER_1MS_SPAN 32
#define TIMER_1MS_TICKS_PER_SEC 1000
#define TIMER_1MS_TIMEOUT_PULSE_OUTPUT 1
#define TIMER_1MS_TYPE "altera_avalon_timer"


/*
 * timer_1us configuration
 *
 */

#define ALT_MODULE_CLASS_timer_1us altera_avalon_timer
#define TIMER_1US_ALWAYS_RUN 1
#define TIMER_1US_BASE 0x80000860
#define TIMER_1US_COUNTER_SIZE 32
#define TIMER_1US_FIXED_PERIOD 0
#define TIMER_1US_FREQ 50000000
#define TIMER_1US_IRQ 1
#define TIMER_1US_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_1US_LOAD_VALUE 49
#define TIMER_1US_MULT 1.0E-6
#define TIMER_1US_NAME "/dev/timer_1us"
#define TIMER_1US_PERIOD 1
#define TIMER_1US_PERIOD_UNITS "us"
#define TIMER_1US_RESET_OUTPUT 0
#define TIMER_1US_SNAPSHOT 1
#define TIMER_1US_SPAN 32
#define TIMER_1US_TICKS_PER_SEC 1000000
#define TIMER_1US_TIMEOUT_PULSE_OUTPUT 1
#define TIMER_1US_TYPE "altera_avalon_timer"


/*
 * ucosii configuration
 *
 */

#define OS_ARG_CHK_EN 1
#define OS_CPU_HOOKS_EN 1
#define OS_DEBUG_EN 1
#define OS_EVENT_NAME_SIZE 32
#define OS_FLAGS_NBITS 16
#define OS_FLAG_ACCEPT_EN 1
#define OS_FLAG_DEL_EN 1
#define OS_FLAG_EN 1
#define OS_FLAG_NAME_SIZE 32
#define OS_FLAG_QUERY_EN 1
#define OS_FLAG_WAIT_CLR_EN 1
#define OS_LOWEST_PRIO 44
#define OS_MAX_EVENTS 128
#define OS_MAX_FLAGS 48
#define OS_MAX_MEM_PART 60
#define OS_MAX_QS 64
#define OS_MAX_TASKS 42
#define OS_MBOX_ACCEPT_EN 0
#define OS_MBOX_DEL_EN 0
#define OS_MBOX_EN 0
#define OS_MBOX_POST_EN 0
#define OS_MBOX_POST_OPT_EN 0
#define OS_MBOX_QUERY_EN 0
#define OS_MEM_EN 1
#define OS_MEM_NAME_SIZE 32
#define OS_MEM_QUERY_EN 1
#define OS_MUTEX_ACCEPT_EN 1
#define OS_MUTEX_DEL_EN 1
#define OS_MUTEX_EN 1
#define OS_MUTEX_QUERY_EN 1
#define OS_Q_ACCEPT_EN 1
#define OS_Q_DEL_EN 1
#define OS_Q_EN 1
#define OS_Q_FLUSH_EN 1
#define OS_Q_POST_EN 1
#define OS_Q_POST_FRONT_EN 1
#define OS_Q_POST_OPT_EN 1
#define OS_Q_QUERY_EN 1
#define OS_SCHED_LOCK_EN 1
#define OS_SEM_ACCEPT_EN 1
#define OS_SEM_DEL_EN 1
#define OS_SEM_EN 1
#define OS_SEM_QUERY_EN 1
#define OS_SEM_SET_EN 1
#define OS_TASK_CHANGE_PRIO_EN 1
#define OS_TASK_CREATE_EN 1
#define OS_TASK_CREATE_EXT_EN 1
#define OS_TASK_DEL_EN 1
#define OS_TASK_IDLE_STK_SIZE 1024
#define OS_TASK_NAME_SIZE 32
#define OS_TASK_PROFILE_EN 1
#define OS_TASK_QUERY_EN 1
#define OS_TASK_STAT_EN 1
#define OS_TASK_STAT_STK_CHK_EN 1
#define OS_TASK_STAT_STK_SIZE 1024
#define OS_TASK_SUSPEND_EN 1
#define OS_TASK_SW_HOOK_EN 1
#define OS_TASK_TMR_PRIO 29
#define OS_TASK_TMR_STK_SIZE 512
#define OS_THREAD_SAFE_NEWLIB 1
#define OS_TICKS_PER_SEC TIMER_1MS_TICKS_PER_SEC
#define OS_TICK_STEP_EN 1
#define OS_TIME_DLY_HMSM_EN 1
#define OS_TIME_DLY_RESUME_EN 1
#define OS_TIME_GET_SET_EN 1
#define OS_TIME_TICK_HOOK_EN 1
#define OS_TMR_CFG_MAX 8
#define OS_TMR_CFG_NAME_SIZE 16
#define OS_TMR_CFG_TICKS_PER_SEC 2
#define OS_TMR_CFG_WHEEL_SIZE 2
#define OS_TMR_EN 1

#endif /* __SYSTEM_H_ */
