	MebX_Qsys_Project u0 (
		.clk50_clk                                            (<connected-to-clk50_clk>),                                            //                      clk50.clk
		.m1_ddr2_memory_mem_a                                 (<connected-to-m1_ddr2_memory_mem_a>),                                 //             m1_ddr2_memory.mem_a
		.m1_ddr2_memory_mem_ba                                (<connected-to-m1_ddr2_memory_mem_ba>),                                //                           .mem_ba
		.m1_ddr2_memory_mem_ck                                (<connected-to-m1_ddr2_memory_mem_ck>),                                //                           .mem_ck
		.m1_ddr2_memory_mem_ck_n                              (<connected-to-m1_ddr2_memory_mem_ck_n>),                              //                           .mem_ck_n
		.m1_ddr2_memory_mem_cke                               (<connected-to-m1_ddr2_memory_mem_cke>),                               //                           .mem_cke
		.m1_ddr2_memory_mem_cs_n                              (<connected-to-m1_ddr2_memory_mem_cs_n>),                              //                           .mem_cs_n
		.m1_ddr2_memory_mem_dm                                (<connected-to-m1_ddr2_memory_mem_dm>),                                //                           .mem_dm
		.m1_ddr2_memory_mem_ras_n                             (<connected-to-m1_ddr2_memory_mem_ras_n>),                             //                           .mem_ras_n
		.m1_ddr2_memory_mem_cas_n                             (<connected-to-m1_ddr2_memory_mem_cas_n>),                             //                           .mem_cas_n
		.m1_ddr2_memory_mem_we_n                              (<connected-to-m1_ddr2_memory_mem_we_n>),                              //                           .mem_we_n
		.m1_ddr2_memory_mem_dq                                (<connected-to-m1_ddr2_memory_mem_dq>),                                //                           .mem_dq
		.m1_ddr2_memory_mem_dqs                               (<connected-to-m1_ddr2_memory_mem_dqs>),                               //                           .mem_dqs
		.m1_ddr2_memory_mem_dqs_n                             (<connected-to-m1_ddr2_memory_mem_dqs_n>),                             //                           .mem_dqs_n
		.m1_ddr2_memory_mem_odt                               (<connected-to-m1_ddr2_memory_mem_odt>),                               //                           .mem_odt
		.m1_ddr2_memory_pll_ref_clk_clk                       (<connected-to-m1_ddr2_memory_pll_ref_clk_clk>),                       // m1_ddr2_memory_pll_ref_clk.clk
		.m1_ddr2_memory_status_local_init_done                (<connected-to-m1_ddr2_memory_status_local_init_done>),                //      m1_ddr2_memory_status.local_init_done
		.m1_ddr2_memory_status_local_cal_success              (<connected-to-m1_ddr2_memory_status_local_cal_success>),              //                           .local_cal_success
		.m1_ddr2_memory_status_local_cal_fail                 (<connected-to-m1_ddr2_memory_status_local_cal_fail>),                 //                           .local_cal_fail
		.m1_ddr2_oct_rdn                                      (<connected-to-m1_ddr2_oct_rdn>),                                      //                m1_ddr2_oct.rdn
		.m1_ddr2_oct_rup                                      (<connected-to-m1_ddr2_oct_rup>),                                      //                           .rup
		.m2_ddr2_memory_mem_a                                 (<connected-to-m2_ddr2_memory_mem_a>),                                 //             m2_ddr2_memory.mem_a
		.m2_ddr2_memory_mem_ba                                (<connected-to-m2_ddr2_memory_mem_ba>),                                //                           .mem_ba
		.m2_ddr2_memory_mem_ck                                (<connected-to-m2_ddr2_memory_mem_ck>),                                //                           .mem_ck
		.m2_ddr2_memory_mem_ck_n                              (<connected-to-m2_ddr2_memory_mem_ck_n>),                              //                           .mem_ck_n
		.m2_ddr2_memory_mem_cke                               (<connected-to-m2_ddr2_memory_mem_cke>),                               //                           .mem_cke
		.m2_ddr2_memory_mem_cs_n                              (<connected-to-m2_ddr2_memory_mem_cs_n>),                              //                           .mem_cs_n
		.m2_ddr2_memory_mem_dm                                (<connected-to-m2_ddr2_memory_mem_dm>),                                //                           .mem_dm
		.m2_ddr2_memory_mem_ras_n                             (<connected-to-m2_ddr2_memory_mem_ras_n>),                             //                           .mem_ras_n
		.m2_ddr2_memory_mem_cas_n                             (<connected-to-m2_ddr2_memory_mem_cas_n>),                             //                           .mem_cas_n
		.m2_ddr2_memory_mem_we_n                              (<connected-to-m2_ddr2_memory_mem_we_n>),                              //                           .mem_we_n
		.m2_ddr2_memory_mem_dq                                (<connected-to-m2_ddr2_memory_mem_dq>),                                //                           .mem_dq
		.m2_ddr2_memory_mem_dqs                               (<connected-to-m2_ddr2_memory_mem_dqs>),                               //                           .mem_dqs
		.m2_ddr2_memory_mem_dqs_n                             (<connected-to-m2_ddr2_memory_mem_dqs_n>),                             //                           .mem_dqs_n
		.m2_ddr2_memory_mem_odt                               (<connected-to-m2_ddr2_memory_mem_odt>),                               //                           .mem_odt
		.m2_ddr2_memory_dll_sharing_dll_pll_locked            (<connected-to-m2_ddr2_memory_dll_sharing_dll_pll_locked>),            // m2_ddr2_memory_dll_sharing.dll_pll_locked
		.m2_ddr2_memory_dll_sharing_dll_delayctrl             (<connected-to-m2_ddr2_memory_dll_sharing_dll_delayctrl>),             //                           .dll_delayctrl
		.m2_ddr2_memory_pll_sharing_pll_mem_clk               (<connected-to-m2_ddr2_memory_pll_sharing_pll_mem_clk>),               // m2_ddr2_memory_pll_sharing.pll_mem_clk
		.m2_ddr2_memory_pll_sharing_pll_write_clk             (<connected-to-m2_ddr2_memory_pll_sharing_pll_write_clk>),             //                           .pll_write_clk
		.m2_ddr2_memory_pll_sharing_pll_locked                (<connected-to-m2_ddr2_memory_pll_sharing_pll_locked>),                //                           .pll_locked
		.m2_ddr2_memory_pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-m2_ddr2_memory_pll_sharing_pll_write_clk_pre_phy_clk>), //                           .pll_write_clk_pre_phy_clk
		.m2_ddr2_memory_pll_sharing_pll_addr_cmd_clk          (<connected-to-m2_ddr2_memory_pll_sharing_pll_addr_cmd_clk>),          //                           .pll_addr_cmd_clk
		.m2_ddr2_memory_pll_sharing_pll_avl_clk               (<connected-to-m2_ddr2_memory_pll_sharing_pll_avl_clk>),               //                           .pll_avl_clk
		.m2_ddr2_memory_pll_sharing_pll_config_clk            (<connected-to-m2_ddr2_memory_pll_sharing_pll_config_clk>),            //                           .pll_config_clk
		.m2_ddr2_memory_status_local_init_done                (<connected-to-m2_ddr2_memory_status_local_init_done>),                //      m2_ddr2_memory_status.local_init_done
		.m2_ddr2_memory_status_local_cal_success              (<connected-to-m2_ddr2_memory_status_local_cal_success>),              //                           .local_cal_success
		.m2_ddr2_memory_status_local_cal_fail                 (<connected-to-m2_ddr2_memory_status_local_cal_fail>),                 //                           .local_cal_fail
		.m2_ddr2_oct_rdn                                      (<connected-to-m2_ddr2_oct_rdn>),                                      //                m2_ddr2_oct.rdn
		.m2_ddr2_oct_rup                                      (<connected-to-m2_ddr2_oct_rup>),                                      //                           .rup
		.rst_reset_n                                          (<connected-to-rst_reset_n>),                                          //                        rst.reset_n
		.spwc_a_enable_spw_rx_enable_signal                   (<connected-to-spwc_a_enable_spw_rx_enable_signal>),                   //              spwc_a_enable.spw_rx_enable_signal
		.spwc_a_enable_spw_tx_enable_signal                   (<connected-to-spwc_a_enable_spw_tx_enable_signal>),                   //                           .spw_tx_enable_signal
		.spwc_a_leds_spw_red_status_led_signal                (<connected-to-spwc_a_leds_spw_red_status_led_signal>),                //                spwc_a_leds.spw_red_status_led_signal
		.spwc_a_leds_spw_green_status_led_signal              (<connected-to-spwc_a_leds_spw_green_status_led_signal>),              //                           .spw_green_status_led_signal
		.spwc_a_lvds_spw_lvds_p_data_in_signal                (<connected-to-spwc_a_lvds_spw_lvds_p_data_in_signal>),                //                spwc_a_lvds.spw_lvds_p_data_in_signal
		.spwc_a_lvds_spw_lvds_n_data_in_signal                (<connected-to-spwc_a_lvds_spw_lvds_n_data_in_signal>),                //                           .spw_lvds_n_data_in_signal
		.spwc_a_lvds_spw_lvds_p_data_out_signal               (<connected-to-spwc_a_lvds_spw_lvds_p_data_out_signal>),               //                           .spw_lvds_p_data_out_signal
		.spwc_a_lvds_spw_lvds_n_data_out_signal               (<connected-to-spwc_a_lvds_spw_lvds_n_data_out_signal>),               //                           .spw_lvds_n_data_out_signal
		.spwc_a_lvds_spw_lvds_p_strobe_out_signal             (<connected-to-spwc_a_lvds_spw_lvds_p_strobe_out_signal>),             //                           .spw_lvds_p_strobe_out_signal
		.spwc_a_lvds_spw_lvds_n_strobe_out_signal             (<connected-to-spwc_a_lvds_spw_lvds_n_strobe_out_signal>),             //                           .spw_lvds_n_strobe_out_signal
		.spwc_a_lvds_spw_lvds_p_strobe_in_signal              (<connected-to-spwc_a_lvds_spw_lvds_p_strobe_in_signal>),              //                           .spw_lvds_p_strobe_in_signal
		.spwc_a_lvds_spw_lvds_n_strobe_in_signal              (<connected-to-spwc_a_lvds_spw_lvds_n_strobe_in_signal>),              //                           .spw_lvds_n_strobe_in_signal
		.spwc_b_enable_spw_rx_enable_signal                   (<connected-to-spwc_b_enable_spw_rx_enable_signal>),                   //              spwc_b_enable.spw_rx_enable_signal
		.spwc_b_enable_spw_tx_enable_signal                   (<connected-to-spwc_b_enable_spw_tx_enable_signal>),                   //                           .spw_tx_enable_signal
		.spwc_b_leds_spw_red_status_led_signal                (<connected-to-spwc_b_leds_spw_red_status_led_signal>),                //                spwc_b_leds.spw_red_status_led_signal
		.spwc_b_leds_spw_green_status_led_signal              (<connected-to-spwc_b_leds_spw_green_status_led_signal>),              //                           .spw_green_status_led_signal
		.spwc_b_lvds_spw_lvds_p_data_in_signal                (<connected-to-spwc_b_lvds_spw_lvds_p_data_in_signal>),                //                spwc_b_lvds.spw_lvds_p_data_in_signal
		.spwc_b_lvds_spw_lvds_n_data_in_signal                (<connected-to-spwc_b_lvds_spw_lvds_n_data_in_signal>),                //                           .spw_lvds_n_data_in_signal
		.spwc_b_lvds_spw_lvds_p_data_out_signal               (<connected-to-spwc_b_lvds_spw_lvds_p_data_out_signal>),               //                           .spw_lvds_p_data_out_signal
		.spwc_b_lvds_spw_lvds_n_data_out_signal               (<connected-to-spwc_b_lvds_spw_lvds_n_data_out_signal>),               //                           .spw_lvds_n_data_out_signal
		.spwc_b_lvds_spw_lvds_p_strobe_out_signal             (<connected-to-spwc_b_lvds_spw_lvds_p_strobe_out_signal>),             //                           .spw_lvds_p_strobe_out_signal
		.spwc_b_lvds_spw_lvds_n_strobe_out_signal             (<connected-to-spwc_b_lvds_spw_lvds_n_strobe_out_signal>),             //                           .spw_lvds_n_strobe_out_signal
		.spwc_b_lvds_spw_lvds_p_strobe_in_signal              (<connected-to-spwc_b_lvds_spw_lvds_p_strobe_in_signal>),              //                           .spw_lvds_p_strobe_in_signal
		.spwc_b_lvds_spw_lvds_n_strobe_in_signal              (<connected-to-spwc_b_lvds_spw_lvds_n_strobe_in_signal>),              //                           .spw_lvds_n_strobe_in_signal
		.spwc_c_enable_spw_rx_enable_signal                   (<connected-to-spwc_c_enable_spw_rx_enable_signal>),                   //              spwc_c_enable.spw_rx_enable_signal
		.spwc_c_enable_spw_tx_enable_signal                   (<connected-to-spwc_c_enable_spw_tx_enable_signal>),                   //                           .spw_tx_enable_signal
		.spwc_c_leds_spw_red_status_led_signal                (<connected-to-spwc_c_leds_spw_red_status_led_signal>),                //                spwc_c_leds.spw_red_status_led_signal
		.spwc_c_leds_spw_green_status_led_signal              (<connected-to-spwc_c_leds_spw_green_status_led_signal>),              //                           .spw_green_status_led_signal
		.spwc_c_lvds_spw_lvds_p_data_in_signal                (<connected-to-spwc_c_lvds_spw_lvds_p_data_in_signal>),                //                spwc_c_lvds.spw_lvds_p_data_in_signal
		.spwc_c_lvds_spw_lvds_n_data_in_signal                (<connected-to-spwc_c_lvds_spw_lvds_n_data_in_signal>),                //                           .spw_lvds_n_data_in_signal
		.spwc_c_lvds_spw_lvds_p_data_out_signal               (<connected-to-spwc_c_lvds_spw_lvds_p_data_out_signal>),               //                           .spw_lvds_p_data_out_signal
		.spwc_c_lvds_spw_lvds_n_data_out_signal               (<connected-to-spwc_c_lvds_spw_lvds_n_data_out_signal>),               //                           .spw_lvds_n_data_out_signal
		.spwc_c_lvds_spw_lvds_p_strobe_out_signal             (<connected-to-spwc_c_lvds_spw_lvds_p_strobe_out_signal>),             //                           .spw_lvds_p_strobe_out_signal
		.spwc_c_lvds_spw_lvds_n_strobe_out_signal             (<connected-to-spwc_c_lvds_spw_lvds_n_strobe_out_signal>),             //                           .spw_lvds_n_strobe_out_signal
		.spwc_c_lvds_spw_lvds_p_strobe_in_signal              (<connected-to-spwc_c_lvds_spw_lvds_p_strobe_in_signal>),              //                           .spw_lvds_p_strobe_in_signal
		.spwc_c_lvds_spw_lvds_n_strobe_in_signal              (<connected-to-spwc_c_lvds_spw_lvds_n_strobe_in_signal>),              //                           .spw_lvds_n_strobe_in_signal
		.spwc_d_enable_spw_rx_enable_signal                   (<connected-to-spwc_d_enable_spw_rx_enable_signal>),                   //              spwc_d_enable.spw_rx_enable_signal
		.spwc_d_enable_spw_tx_enable_signal                   (<connected-to-spwc_d_enable_spw_tx_enable_signal>),                   //                           .spw_tx_enable_signal
		.spwc_d_leds_spw_red_status_led_signal                (<connected-to-spwc_d_leds_spw_red_status_led_signal>),                //                spwc_d_leds.spw_red_status_led_signal
		.spwc_d_leds_spw_green_status_led_signal              (<connected-to-spwc_d_leds_spw_green_status_led_signal>),              //                           .spw_green_status_led_signal
		.spwc_d_lvds_spw_lvds_p_data_in_signal                (<connected-to-spwc_d_lvds_spw_lvds_p_data_in_signal>),                //                spwc_d_lvds.spw_lvds_p_data_in_signal
		.spwc_d_lvds_spw_lvds_n_data_in_signal                (<connected-to-spwc_d_lvds_spw_lvds_n_data_in_signal>),                //                           .spw_lvds_n_data_in_signal
		.spwc_d_lvds_spw_lvds_p_data_out_signal               (<connected-to-spwc_d_lvds_spw_lvds_p_data_out_signal>),               //                           .spw_lvds_p_data_out_signal
		.spwc_d_lvds_spw_lvds_n_data_out_signal               (<connected-to-spwc_d_lvds_spw_lvds_n_data_out_signal>),               //                           .spw_lvds_n_data_out_signal
		.spwc_d_lvds_spw_lvds_p_strobe_out_signal             (<connected-to-spwc_d_lvds_spw_lvds_p_strobe_out_signal>),             //                           .spw_lvds_p_strobe_out_signal
		.spwc_d_lvds_spw_lvds_n_strobe_out_signal             (<connected-to-spwc_d_lvds_spw_lvds_n_strobe_out_signal>),             //                           .spw_lvds_n_strobe_out_signal
		.spwc_d_lvds_spw_lvds_p_strobe_in_signal              (<connected-to-spwc_d_lvds_spw_lvds_p_strobe_in_signal>),              //                           .spw_lvds_p_strobe_in_signal
		.spwc_d_lvds_spw_lvds_n_strobe_in_signal              (<connected-to-spwc_d_lvds_spw_lvds_n_strobe_in_signal>),              //                           .spw_lvds_n_strobe_in_signal
		.spwc_e_enable_spw_rx_enable_signal                   (<connected-to-spwc_e_enable_spw_rx_enable_signal>),                   //              spwc_e_enable.spw_rx_enable_signal
		.spwc_e_enable_spw_tx_enable_signal                   (<connected-to-spwc_e_enable_spw_tx_enable_signal>),                   //                           .spw_tx_enable_signal
		.spwc_e_leds_spw_red_status_led_signal                (<connected-to-spwc_e_leds_spw_red_status_led_signal>),                //                spwc_e_leds.spw_red_status_led_signal
		.spwc_e_leds_spw_green_status_led_signal              (<connected-to-spwc_e_leds_spw_green_status_led_signal>),              //                           .spw_green_status_led_signal
		.spwc_e_lvds_spw_lvds_p_data_in_signal                (<connected-to-spwc_e_lvds_spw_lvds_p_data_in_signal>),                //                spwc_e_lvds.spw_lvds_p_data_in_signal
		.spwc_e_lvds_spw_lvds_n_data_in_signal                (<connected-to-spwc_e_lvds_spw_lvds_n_data_in_signal>),                //                           .spw_lvds_n_data_in_signal
		.spwc_e_lvds_spw_lvds_p_data_out_signal               (<connected-to-spwc_e_lvds_spw_lvds_p_data_out_signal>),               //                           .spw_lvds_p_data_out_signal
		.spwc_e_lvds_spw_lvds_n_data_out_signal               (<connected-to-spwc_e_lvds_spw_lvds_n_data_out_signal>),               //                           .spw_lvds_n_data_out_signal
		.spwc_e_lvds_spw_lvds_p_strobe_out_signal             (<connected-to-spwc_e_lvds_spw_lvds_p_strobe_out_signal>),             //                           .spw_lvds_p_strobe_out_signal
		.spwc_e_lvds_spw_lvds_n_strobe_out_signal             (<connected-to-spwc_e_lvds_spw_lvds_n_strobe_out_signal>),             //                           .spw_lvds_n_strobe_out_signal
		.spwc_e_lvds_spw_lvds_p_strobe_in_signal              (<connected-to-spwc_e_lvds_spw_lvds_p_strobe_in_signal>),              //                           .spw_lvds_p_strobe_in_signal
		.spwc_e_lvds_spw_lvds_n_strobe_in_signal              (<connected-to-spwc_e_lvds_spw_lvds_n_strobe_in_signal>),              //                           .spw_lvds_n_strobe_in_signal
		.spwc_f_enable_spw_rx_enable_signal                   (<connected-to-spwc_f_enable_spw_rx_enable_signal>),                   //              spwc_f_enable.spw_rx_enable_signal
		.spwc_f_enable_spw_tx_enable_signal                   (<connected-to-spwc_f_enable_spw_tx_enable_signal>),                   //                           .spw_tx_enable_signal
		.spwc_f_leds_spw_red_status_led_signal                (<connected-to-spwc_f_leds_spw_red_status_led_signal>),                //                spwc_f_leds.spw_red_status_led_signal
		.spwc_f_leds_spw_green_status_led_signal              (<connected-to-spwc_f_leds_spw_green_status_led_signal>),              //                           .spw_green_status_led_signal
		.spwc_f_lvds_spw_lvds_p_data_in_signal                (<connected-to-spwc_f_lvds_spw_lvds_p_data_in_signal>),                //                spwc_f_lvds.spw_lvds_p_data_in_signal
		.spwc_f_lvds_spw_lvds_n_data_in_signal                (<connected-to-spwc_f_lvds_spw_lvds_n_data_in_signal>),                //                           .spw_lvds_n_data_in_signal
		.spwc_f_lvds_spw_lvds_p_data_out_signal               (<connected-to-spwc_f_lvds_spw_lvds_p_data_out_signal>),               //                           .spw_lvds_p_data_out_signal
		.spwc_f_lvds_spw_lvds_n_data_out_signal               (<connected-to-spwc_f_lvds_spw_lvds_n_data_out_signal>),               //                           .spw_lvds_n_data_out_signal
		.spwc_f_lvds_spw_lvds_p_strobe_out_signal             (<connected-to-spwc_f_lvds_spw_lvds_p_strobe_out_signal>),             //                           .spw_lvds_p_strobe_out_signal
		.spwc_f_lvds_spw_lvds_n_strobe_out_signal             (<connected-to-spwc_f_lvds_spw_lvds_n_strobe_out_signal>),             //                           .spw_lvds_n_strobe_out_signal
		.spwc_f_lvds_spw_lvds_p_strobe_in_signal              (<connected-to-spwc_f_lvds_spw_lvds_p_strobe_in_signal>),              //                           .spw_lvds_p_strobe_in_signal
		.spwc_f_lvds_spw_lvds_n_strobe_in_signal              (<connected-to-spwc_f_lvds_spw_lvds_n_strobe_in_signal>),              //                           .spw_lvds_n_strobe_in_signal
		.spwc_g_enable_spw_rx_enable_signal                   (<connected-to-spwc_g_enable_spw_rx_enable_signal>),                   //              spwc_g_enable.spw_rx_enable_signal
		.spwc_g_enable_spw_tx_enable_signal                   (<connected-to-spwc_g_enable_spw_tx_enable_signal>),                   //                           .spw_tx_enable_signal
		.spwc_g_leds_spw_red_status_led_signal                (<connected-to-spwc_g_leds_spw_red_status_led_signal>),                //                spwc_g_leds.spw_red_status_led_signal
		.spwc_g_leds_spw_green_status_led_signal              (<connected-to-spwc_g_leds_spw_green_status_led_signal>),              //                           .spw_green_status_led_signal
		.spwc_g_lvds_spw_lvds_p_data_in_signal                (<connected-to-spwc_g_lvds_spw_lvds_p_data_in_signal>),                //                spwc_g_lvds.spw_lvds_p_data_in_signal
		.spwc_g_lvds_spw_lvds_n_data_in_signal                (<connected-to-spwc_g_lvds_spw_lvds_n_data_in_signal>),                //                           .spw_lvds_n_data_in_signal
		.spwc_g_lvds_spw_lvds_p_data_out_signal               (<connected-to-spwc_g_lvds_spw_lvds_p_data_out_signal>),               //                           .spw_lvds_p_data_out_signal
		.spwc_g_lvds_spw_lvds_n_data_out_signal               (<connected-to-spwc_g_lvds_spw_lvds_n_data_out_signal>),               //                           .spw_lvds_n_data_out_signal
		.spwc_g_lvds_spw_lvds_p_strobe_out_signal             (<connected-to-spwc_g_lvds_spw_lvds_p_strobe_out_signal>),             //                           .spw_lvds_p_strobe_out_signal
		.spwc_g_lvds_spw_lvds_n_strobe_out_signal             (<connected-to-spwc_g_lvds_spw_lvds_n_strobe_out_signal>),             //                           .spw_lvds_n_strobe_out_signal
		.spwc_g_lvds_spw_lvds_p_strobe_in_signal              (<connected-to-spwc_g_lvds_spw_lvds_p_strobe_in_signal>),              //                           .spw_lvds_p_strobe_in_signal
		.spwc_g_lvds_spw_lvds_n_strobe_in_signal              (<connected-to-spwc_g_lvds_spw_lvds_n_strobe_in_signal>),              //                           .spw_lvds_n_strobe_in_signal
		.spwc_h_enable_spw_rx_enable_signal                   (<connected-to-spwc_h_enable_spw_rx_enable_signal>),                   //              spwc_h_enable.spw_rx_enable_signal
		.spwc_h_enable_spw_tx_enable_signal                   (<connected-to-spwc_h_enable_spw_tx_enable_signal>),                   //                           .spw_tx_enable_signal
		.spwc_h_leds_spw_red_status_led_signal                (<connected-to-spwc_h_leds_spw_red_status_led_signal>),                //                spwc_h_leds.spw_red_status_led_signal
		.spwc_h_leds_spw_green_status_led_signal              (<connected-to-spwc_h_leds_spw_green_status_led_signal>),              //                           .spw_green_status_led_signal
		.spwc_h_lvds_spw_lvds_p_data_in_signal                (<connected-to-spwc_h_lvds_spw_lvds_p_data_in_signal>),                //                spwc_h_lvds.spw_lvds_p_data_in_signal
		.spwc_h_lvds_spw_lvds_n_data_in_signal                (<connected-to-spwc_h_lvds_spw_lvds_n_data_in_signal>),                //                           .spw_lvds_n_data_in_signal
		.spwc_h_lvds_spw_lvds_p_data_out_signal               (<connected-to-spwc_h_lvds_spw_lvds_p_data_out_signal>),               //                           .spw_lvds_p_data_out_signal
		.spwc_h_lvds_spw_lvds_n_data_out_signal               (<connected-to-spwc_h_lvds_spw_lvds_n_data_out_signal>),               //                           .spw_lvds_n_data_out_signal
		.spwc_h_lvds_spw_lvds_p_strobe_out_signal             (<connected-to-spwc_h_lvds_spw_lvds_p_strobe_out_signal>),             //                           .spw_lvds_p_strobe_out_signal
		.spwc_h_lvds_spw_lvds_n_strobe_out_signal             (<connected-to-spwc_h_lvds_spw_lvds_n_strobe_out_signal>),             //                           .spw_lvds_n_strobe_out_signal
		.spwc_h_lvds_spw_lvds_p_strobe_in_signal              (<connected-to-spwc_h_lvds_spw_lvds_p_strobe_in_signal>),              //                           .spw_lvds_p_strobe_in_signal
		.spwc_h_lvds_spw_lvds_n_strobe_in_signal              (<connected-to-spwc_h_lvds_spw_lvds_n_strobe_in_signal>),              //                           .spw_lvds_n_strobe_in_signal
		.spwr_drivers_isolator_en_drivers_isolator_en_signal  (<connected-to-spwr_drivers_isolator_en_drivers_isolator_en_signal>),  //   spwr_drivers_isolator_en.drivers_isolator_en_signal
		.spwr_router_control_router_config_en_signal          (<connected-to-spwr_router_control_router_config_en_signal>),          //        spwr_router_control.router_config_en_signal
		.spwr_router_control_router_path_0_select_signal      (<connected-to-spwr_router_control_router_path_0_select_signal>),      //                           .router_path_0_select_signal
		.spwr_router_control_router_path_1_select_signal      (<connected-to-spwr_router_control_router_path_1_select_signal>),      //                           .router_path_1_select_signal
		.m1_ddr2_memory_avl_waitrequest_n                     (<connected-to-m1_ddr2_memory_avl_waitrequest_n>),                     //         m1_ddr2_memory_avl.waitrequest_n
		.m1_ddr2_memory_avl_beginbursttransfer                (<connected-to-m1_ddr2_memory_avl_beginbursttransfer>),                //                           .beginbursttransfer
		.m1_ddr2_memory_avl_address                           (<connected-to-m1_ddr2_memory_avl_address>),                           //                           .address
		.m1_ddr2_memory_avl_readdatavalid                     (<connected-to-m1_ddr2_memory_avl_readdatavalid>),                     //                           .readdatavalid
		.m1_ddr2_memory_avl_readdata                          (<connected-to-m1_ddr2_memory_avl_readdata>),                          //                           .readdata
		.m1_ddr2_memory_avl_writedata                         (<connected-to-m1_ddr2_memory_avl_writedata>),                         //                           .writedata
		.m1_ddr2_memory_avl_byteenable                        (<connected-to-m1_ddr2_memory_avl_byteenable>),                        //                           .byteenable
		.m1_ddr2_memory_avl_read                              (<connected-to-m1_ddr2_memory_avl_read>),                              //                           .read
		.m1_ddr2_memory_avl_write                             (<connected-to-m1_ddr2_memory_avl_write>),                             //                           .write
		.m1_ddr2_memory_avl_burstcount                        (<connected-to-m1_ddr2_memory_avl_burstcount>),                        //                           .burstcount
		.m2_ddr2_memory_avl_waitrequest_n                     (<connected-to-m2_ddr2_memory_avl_waitrequest_n>),                     //         m2_ddr2_memory_avl.waitrequest_n
		.m2_ddr2_memory_avl_beginbursttransfer                (<connected-to-m2_ddr2_memory_avl_beginbursttransfer>),                //                           .beginbursttransfer
		.m2_ddr2_memory_avl_address                           (<connected-to-m2_ddr2_memory_avl_address>),                           //                           .address
		.m2_ddr2_memory_avl_readdatavalid                     (<connected-to-m2_ddr2_memory_avl_readdatavalid>),                     //                           .readdatavalid
		.m2_ddr2_memory_avl_readdata                          (<connected-to-m2_ddr2_memory_avl_readdata>),                          //                           .readdata
		.m2_ddr2_memory_avl_writedata                         (<connected-to-m2_ddr2_memory_avl_writedata>),                         //                           .writedata
		.m2_ddr2_memory_avl_byteenable                        (<connected-to-m2_ddr2_memory_avl_byteenable>),                        //                           .byteenable
		.m2_ddr2_memory_avl_read                              (<connected-to-m2_ddr2_memory_avl_read>),                              //                           .read
		.m2_ddr2_memory_avl_write                             (<connected-to-m2_ddr2_memory_avl_write>),                             //                           .write
		.m2_ddr2_memory_avl_burstcount                        (<connected-to-m2_ddr2_memory_avl_burstcount>)                         //                           .burstcount
	);

