/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'MebX_Qsys_Project'
 * SOPC Builder design path: ../../MebX_Qsys_Project.sopcinfo
 *
 * Generated: Wed May 02 11:10:46 BRT 2018
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x81201020
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x20
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x81100020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 1
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 1
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_DIVISION_ERROR_EXCEPTION
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INST_ADDR_WIDTH 0x20
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x86020000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x81201020
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x20
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x81100020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 1
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 1
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_DIVISION_ERROR_EXCEPTION
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INST_ADDR_WIDTH 0x20
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x86020000


/*
 * Communication_Module_A configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_A Communication_Module
#define COMMUNICATION_MODULE_A_BASE 0x81203400
#define COMMUNICATION_MODULE_A_IRQ -1
#define COMMUNICATION_MODULE_A_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_A_NAME "/dev/Communication_Module_A"
#define COMMUNICATION_MODULE_A_SPAN 1024
#define COMMUNICATION_MODULE_A_TYPE "Communication_Module"


/*
 * Communication_Module_B configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_B Communication_Module
#define COMMUNICATION_MODULE_B_BASE 0x81203000
#define COMMUNICATION_MODULE_B_IRQ -1
#define COMMUNICATION_MODULE_B_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_B_NAME "/dev/Communication_Module_B"
#define COMMUNICATION_MODULE_B_SPAN 1024
#define COMMUNICATION_MODULE_B_TYPE "Communication_Module"


/*
 * Communication_Module_C configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_C Communication_Module
#define COMMUNICATION_MODULE_C_BASE 0x81202c00
#define COMMUNICATION_MODULE_C_IRQ -1
#define COMMUNICATION_MODULE_C_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_C_NAME "/dev/Communication_Module_C"
#define COMMUNICATION_MODULE_C_SPAN 1024
#define COMMUNICATION_MODULE_C_TYPE "Communication_Module"


/*
 * Communication_Module_D configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_D Communication_Module
#define COMMUNICATION_MODULE_D_BASE 0x81202800
#define COMMUNICATION_MODULE_D_IRQ -1
#define COMMUNICATION_MODULE_D_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_D_NAME "/dev/Communication_Module_D"
#define COMMUNICATION_MODULE_D_SPAN 1024
#define COMMUNICATION_MODULE_D_TYPE "Communication_Module"


/*
 * Communication_Module_E configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_E Communication_Module
#define COMMUNICATION_MODULE_E_BASE 0x81202400
#define COMMUNICATION_MODULE_E_IRQ -1
#define COMMUNICATION_MODULE_E_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_E_NAME "/dev/Communication_Module_E"
#define COMMUNICATION_MODULE_E_SPAN 1024
#define COMMUNICATION_MODULE_E_TYPE "Communication_Module"


/*
 * Communication_Module_F configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_F Communication_Module
#define COMMUNICATION_MODULE_F_BASE 0x81202000
#define COMMUNICATION_MODULE_F_IRQ -1
#define COMMUNICATION_MODULE_F_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_F_NAME "/dev/Communication_Module_F"
#define COMMUNICATION_MODULE_F_SPAN 1024
#define COMMUNICATION_MODULE_F_TYPE "Communication_Module"


/*
 * Communication_Module_G configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_G Communication_Module
#define COMMUNICATION_MODULE_G_BASE 0x81201c00
#define COMMUNICATION_MODULE_G_IRQ -1
#define COMMUNICATION_MODULE_G_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_G_NAME "/dev/Communication_Module_G"
#define COMMUNICATION_MODULE_G_SPAN 1024
#define COMMUNICATION_MODULE_G_TYPE "Communication_Module"


/*
 * Communication_Module_H configuration
 *
 */

#define ALT_MODULE_CLASS_Communication_Module_H Communication_Module
#define COMMUNICATION_MODULE_H_BASE 0x81201800
#define COMMUNICATION_MODULE_H_IRQ -1
#define COMMUNICATION_MODULE_H_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COMMUNICATION_MODULE_H_NAME "/dev/Communication_Module_H"
#define COMMUNICATION_MODULE_H_SPAN 1024
#define COMMUNICATION_MODULE_H_TYPE "Communication_Module"


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_ADDRESS_SPAN_EXTENDER
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_ETH_TSE
#define __ALTERA_GENERIC_TRISTATE_CONTROLLER
#define __ALTERA_MSGDMA
#define __ALTERA_NIOS2_GEN2
#define __COMMUNICATION_MODULE
#define __PATTERN_GENERATOR
#define __SEVEN_SEGMENT_CONTROLLER


/*
 * Pattern_Generator_A configuration
 *
 */

#define ALT_MODULE_CLASS_Pattern_Generator_A Pattern_Generator
#define PATTERN_GENERATOR_A_BASE 0x81203c00
#define PATTERN_GENERATOR_A_IRQ -1
#define PATTERN_GENERATOR_A_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PATTERN_GENERATOR_A_NAME "/dev/Pattern_Generator_A"
#define PATTERN_GENERATOR_A_SPAN 1024
#define PATTERN_GENERATOR_A_TYPE "Pattern_Generator"


/*
 * SEVEN_SEGMENT_CONTROLLER_0 configuration
 *
 */

#define ALT_MODULE_CLASS_SEVEN_SEGMENT_CONTROLLER_0 SEVEN_SEGMENT_CONTROLLER
#define SEVEN_SEGMENT_CONTROLLER_0_BASE 0x80000200
#define SEVEN_SEGMENT_CONTROLLER_0_IRQ -1
#define SEVEN_SEGMENT_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEVEN_SEGMENT_CONTROLLER_0_NAME "/dev/SEVEN_SEGMENT_CONTROLLER_0"
#define SEVEN_SEGMENT_CONTROLLER_0_SPAN 8
#define SEVEN_SEGMENT_CONTROLLER_0_TYPE "SEVEN_SEGMENT_CONTROLLER"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Stratix IV"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x812040d0
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x812040d0
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x812040d0
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "MebX_Qsys_Project"


/*
 * altera_iniche configuration
 *
 */

#define DHCP_CLIENT
#define INCLUDE_TCP
#define INICHE_DEFAULT_IF "NOT_USED"
#define IP_FRAGMENTS


/*
 * csense_adc_fo configuration
 *
 */

#define ALT_MODULE_CLASS_csense_adc_fo altera_avalon_pio
#define CSENSE_ADC_FO_BASE 0x800000d0
#define CSENSE_ADC_FO_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_ADC_FO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_ADC_FO_CAPTURE 0
#define CSENSE_ADC_FO_DATA_WIDTH 1
#define CSENSE_ADC_FO_DO_TEST_BENCH_WIRING 0
#define CSENSE_ADC_FO_DRIVEN_SIM_VALUE 0
#define CSENSE_ADC_FO_EDGE_TYPE "NONE"
#define CSENSE_ADC_FO_FREQ 50000000
#define CSENSE_ADC_FO_HAS_IN 0
#define CSENSE_ADC_FO_HAS_OUT 1
#define CSENSE_ADC_FO_HAS_TRI 0
#define CSENSE_ADC_FO_IRQ -1
#define CSENSE_ADC_FO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_ADC_FO_IRQ_TYPE "NONE"
#define CSENSE_ADC_FO_NAME "/dev/csense_adc_fo"
#define CSENSE_ADC_FO_RESET_VALUE 0
#define CSENSE_ADC_FO_SPAN 16
#define CSENSE_ADC_FO_TYPE "altera_avalon_pio"


/*
 * csense_cs_n configuration
 *
 */

#define ALT_MODULE_CLASS_csense_cs_n altera_avalon_pio
#define CSENSE_CS_N_BASE 0x800000e0
#define CSENSE_CS_N_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_CS_N_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_CS_N_CAPTURE 0
#define CSENSE_CS_N_DATA_WIDTH 2
#define CSENSE_CS_N_DO_TEST_BENCH_WIRING 0
#define CSENSE_CS_N_DRIVEN_SIM_VALUE 0
#define CSENSE_CS_N_EDGE_TYPE "NONE"
#define CSENSE_CS_N_FREQ 50000000
#define CSENSE_CS_N_HAS_IN 0
#define CSENSE_CS_N_HAS_OUT 1
#define CSENSE_CS_N_HAS_TRI 0
#define CSENSE_CS_N_IRQ -1
#define CSENSE_CS_N_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_CS_N_IRQ_TYPE "NONE"
#define CSENSE_CS_N_NAME "/dev/csense_cs_n"
#define CSENSE_CS_N_RESET_VALUE 0
#define CSENSE_CS_N_SPAN 16
#define CSENSE_CS_N_TYPE "altera_avalon_pio"


/*
 * csense_sck configuration
 *
 */

#define ALT_MODULE_CLASS_csense_sck altera_avalon_pio
#define CSENSE_SCK_BASE 0x800000f0
#define CSENSE_SCK_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_SCK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_SCK_CAPTURE 0
#define CSENSE_SCK_DATA_WIDTH 1
#define CSENSE_SCK_DO_TEST_BENCH_WIRING 0
#define CSENSE_SCK_DRIVEN_SIM_VALUE 0
#define CSENSE_SCK_EDGE_TYPE "NONE"
#define CSENSE_SCK_FREQ 50000000
#define CSENSE_SCK_HAS_IN 0
#define CSENSE_SCK_HAS_OUT 1
#define CSENSE_SCK_HAS_TRI 0
#define CSENSE_SCK_IRQ -1
#define CSENSE_SCK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_SCK_IRQ_TYPE "NONE"
#define CSENSE_SCK_NAME "/dev/csense_sck"
#define CSENSE_SCK_RESET_VALUE 0
#define CSENSE_SCK_SPAN 16
#define CSENSE_SCK_TYPE "altera_avalon_pio"


/*
 * csense_sdi configuration
 *
 */

#define ALT_MODULE_CLASS_csense_sdi altera_avalon_pio
#define CSENSE_SDI_BASE 0x80000100
#define CSENSE_SDI_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_SDI_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_SDI_CAPTURE 0
#define CSENSE_SDI_DATA_WIDTH 1
#define CSENSE_SDI_DO_TEST_BENCH_WIRING 0
#define CSENSE_SDI_DRIVEN_SIM_VALUE 0
#define CSENSE_SDI_EDGE_TYPE "NONE"
#define CSENSE_SDI_FREQ 50000000
#define CSENSE_SDI_HAS_IN 0
#define CSENSE_SDI_HAS_OUT 1
#define CSENSE_SDI_HAS_TRI 0
#define CSENSE_SDI_IRQ -1
#define CSENSE_SDI_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_SDI_IRQ_TYPE "NONE"
#define CSENSE_SDI_NAME "/dev/csense_sdi"
#define CSENSE_SDI_RESET_VALUE 0
#define CSENSE_SDI_SPAN 16
#define CSENSE_SDI_TYPE "altera_avalon_pio"


/*
 * csense_sdo configuration
 *
 */

#define ALT_MODULE_CLASS_csense_sdo altera_avalon_pio
#define CSENSE_SDO_BASE 0x80000110
#define CSENSE_SDO_BIT_CLEARING_EDGE_REGISTER 0
#define CSENSE_SDO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSENSE_SDO_CAPTURE 0
#define CSENSE_SDO_DATA_WIDTH 1
#define CSENSE_SDO_DO_TEST_BENCH_WIRING 0
#define CSENSE_SDO_DRIVEN_SIM_VALUE 0
#define CSENSE_SDO_EDGE_TYPE "NONE"
#define CSENSE_SDO_FREQ 50000000
#define CSENSE_SDO_HAS_IN 1
#define CSENSE_SDO_HAS_OUT 0
#define CSENSE_SDO_HAS_TRI 0
#define CSENSE_SDO_IRQ -1
#define CSENSE_SDO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CSENSE_SDO_IRQ_TYPE "NONE"
#define CSENSE_SDO_NAME "/dev/csense_sdo"
#define CSENSE_SDO_RESET_VALUE 0
#define CSENSE_SDO_SPAN 16
#define CSENSE_SDO_TYPE "altera_avalon_pio"


/*
 * ddr2_address_span_extender_cntl configuration
 *
 */

#define ALT_MODULE_CLASS_ddr2_address_span_extender_cntl altera_address_span_extender
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_BASE 0x812040c8
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_BURSTCOUNT_WIDTH 8
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_BYTEENABLE_WIDTH 4
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_CNTL_ADDRESS_WIDTH 1
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_DATA_WIDTH 32
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_IRQ -1
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_MASTER_ADDRESS_WIDTH 0x20
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_MAX_BURST_BYTES 512
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_MAX_BURST_WORDS 128
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_NAME "/dev/ddr2_address_span_extender_cntl"
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_SLAVE_ADDRESS_SHIFT 0x2
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_SLAVE_ADDRESS_WIDTH 0x1d
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_SPAN 8
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_SUB_WINDOW_COUNT 1
#define DDR2_ADDRESS_SPAN_EXTENDER_CNTL_TYPE "altera_address_span_extender"


/*
 * ddr2_address_span_extender_windowed_slave configuration
 *
 */

#define ALT_MODULE_CLASS_ddr2_address_span_extender_windowed_slave altera_address_span_extender
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_BASE 0x0
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_BURSTCOUNT_WIDTH 8
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_BYTEENABLE_WIDTH 4
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_CNTL_ADDRESS_WIDTH 1
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_DATA_WIDTH 32
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_IRQ -1
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_MASTER_ADDRESS_WIDTH 0x20
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_MAX_BURST_BYTES 512
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_MAX_BURST_WORDS 128
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_NAME "/dev/ddr2_address_span_extender_windowed_slave"
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_SLAVE_ADDRESS_SHIFT 0x2
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_SLAVE_ADDRESS_WIDTH 0x1d
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_SPAN 2147483648
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_SUB_WINDOW_COUNT 1
#define DDR2_ADDRESS_SPAN_EXTENDER_WINDOWED_SLAVE_TYPE "altera_address_span_extender"


/*
 * descriptor_memory configuration
 *
 */

#define ALT_MODULE_CLASS_descriptor_memory altera_avalon_onchip_memory2
#define DESCRIPTOR_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DESCRIPTOR_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DESCRIPTOR_MEMORY_BASE 0x81200800
#define DESCRIPTOR_MEMORY_CONTENTS_INFO ""
#define DESCRIPTOR_MEMORY_DUAL_PORT 0
#define DESCRIPTOR_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define DESCRIPTOR_MEMORY_INIT_CONTENTS_FILE "MebX_Qsys_Project_descriptor_memory"
#define DESCRIPTOR_MEMORY_INIT_MEM_CONTENT 1
#define DESCRIPTOR_MEMORY_INSTANCE_ID "NONE"
#define DESCRIPTOR_MEMORY_IRQ -1
#define DESCRIPTOR_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DESCRIPTOR_MEMORY_NAME "/dev/descriptor_memory"
#define DESCRIPTOR_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DESCRIPTOR_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define DESCRIPTOR_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define DESCRIPTOR_MEMORY_SINGLE_CLOCK_OP 0
#define DESCRIPTOR_MEMORY_SIZE_MULTIPLE 1
#define DESCRIPTOR_MEMORY_SIZE_VALUE 2048
#define DESCRIPTOR_MEMORY_SPAN 2048
#define DESCRIPTOR_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define DESCRIPTOR_MEMORY_WRITABLE 1


/*
 * dma_DDR_M_csr configuration
 *
 */

#define ALT_MODULE_CLASS_dma_DDR_M_csr altera_msgdma
#define DMA_DDR_M_CSR_BASE 0x812040a0
#define DMA_DDR_M_CSR_BURST_ENABLE 1
#define DMA_DDR_M_CSR_BURST_WRAPPING_SUPPORT 0
#define DMA_DDR_M_CSR_CHANNEL_ENABLE 0
#define DMA_DDR_M_CSR_CHANNEL_ENABLE_DERIVED 0
#define DMA_DDR_M_CSR_CHANNEL_WIDTH 8
#define DMA_DDR_M_CSR_DATA_FIFO_DEPTH 64
#define DMA_DDR_M_CSR_DATA_WIDTH 64
#define DMA_DDR_M_CSR_DESCRIPTOR_FIFO_DEPTH 32
#define DMA_DDR_M_CSR_DMA_MODE 0
#define DMA_DDR_M_CSR_ENHANCED_FEATURES 1
#define DMA_DDR_M_CSR_ERROR_ENABLE 0
#define DMA_DDR_M_CSR_ERROR_ENABLE_DERIVED 0
#define DMA_DDR_M_CSR_ERROR_WIDTH 8
#define DMA_DDR_M_CSR_IRQ 7
#define DMA_DDR_M_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define DMA_DDR_M_CSR_MAX_BURST_COUNT 16
#define DMA_DDR_M_CSR_MAX_BYTE 67108864
#define DMA_DDR_M_CSR_MAX_STRIDE 1
#define DMA_DDR_M_CSR_NAME "/dev/dma_DDR_M_csr"
#define DMA_DDR_M_CSR_PACKET_ENABLE 0
#define DMA_DDR_M_CSR_PACKET_ENABLE_DERIVED 0
#define DMA_DDR_M_CSR_PREFETCHER_ENABLE 0
#define DMA_DDR_M_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define DMA_DDR_M_CSR_RESPONSE_PORT 2
#define DMA_DDR_M_CSR_SPAN 32
#define DMA_DDR_M_CSR_STRIDE_ENABLE 0
#define DMA_DDR_M_CSR_STRIDE_ENABLE_DERIVED 0
#define DMA_DDR_M_CSR_TRANSFER_TYPE "Aligned Accesses"
#define DMA_DDR_M_CSR_TYPE "altera_msgdma"


/*
 * dma_DDR_M_descriptor_slave configuration
 *
 */

#define ALT_MODULE_CLASS_dma_DDR_M_descriptor_slave altera_msgdma
#define DMA_DDR_M_DESCRIPTOR_SLAVE_BASE 0x81204080
#define DMA_DDR_M_DESCRIPTOR_SLAVE_BURST_ENABLE 1
#define DMA_DDR_M_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define DMA_DDR_M_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 64
#define DMA_DDR_M_DESCRIPTOR_SLAVE_DATA_WIDTH 64
#define DMA_DDR_M_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 32
#define DMA_DDR_M_DESCRIPTOR_SLAVE_DMA_MODE 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 1
#define DMA_DDR_M_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define DMA_DDR_M_DESCRIPTOR_SLAVE_IRQ -1
#define DMA_DDR_M_DESCRIPTOR_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_DDR_M_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 16
#define DMA_DDR_M_DESCRIPTOR_SLAVE_MAX_BYTE 67108864
#define DMA_DDR_M_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define DMA_DDR_M_DESCRIPTOR_SLAVE_NAME "/dev/dma_DDR_M_descriptor_slave"
#define DMA_DDR_M_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define DMA_DDR_M_DESCRIPTOR_SLAVE_SPAN 32
#define DMA_DDR_M_DESCRIPTOR_SLAVE_STRIDE_ENABLE 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 0
#define DMA_DDR_M_DESCRIPTOR_SLAVE_TRANSFER_TYPE "Aligned Accesses"
#define DMA_DDR_M_DESCRIPTOR_SLAVE_TYPE "altera_msgdma"


/*
 * ext_flash configuration
 *
 */

#define ALT_MODULE_CLASS_ext_flash altera_generic_tristate_controller
#define EXT_FLASH_BASE 0x84000000
#define EXT_FLASH_HOLD_VALUE 20
#define EXT_FLASH_IRQ -1
#define EXT_FLASH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXT_FLASH_NAME "/dev/ext_flash"
#define EXT_FLASH_SETUP_VALUE 25
#define EXT_FLASH_SIZE 33554432u
#define EXT_FLASH_SPAN 67108864
#define EXT_FLASH_TIMING_UNITS "ns"
#define EXT_FLASH_TYPE "altera_generic_tristate_controller"
#define EXT_FLASH_WAIT_VALUE 100


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER_1MS
#define ALT_TIMESTAMP_CLK TIMER_1MS


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x812040d0
#define JTAG_UART_0_IRQ 2
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * m1_ddr2_i2c_scl configuration
 *
 */

#define ALT_MODULE_CLASS_m1_ddr2_i2c_scl altera_avalon_pio
#define M1_DDR2_I2C_SCL_BASE 0x800001e0
#define M1_DDR2_I2C_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define M1_DDR2_I2C_SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define M1_DDR2_I2C_SCL_CAPTURE 0
#define M1_DDR2_I2C_SCL_DATA_WIDTH 1
#define M1_DDR2_I2C_SCL_DO_TEST_BENCH_WIRING 0
#define M1_DDR2_I2C_SCL_DRIVEN_SIM_VALUE 0
#define M1_DDR2_I2C_SCL_EDGE_TYPE "NONE"
#define M1_DDR2_I2C_SCL_FREQ 50000000
#define M1_DDR2_I2C_SCL_HAS_IN 0
#define M1_DDR2_I2C_SCL_HAS_OUT 1
#define M1_DDR2_I2C_SCL_HAS_TRI 0
#define M1_DDR2_I2C_SCL_IRQ -1
#define M1_DDR2_I2C_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define M1_DDR2_I2C_SCL_IRQ_TYPE "NONE"
#define M1_DDR2_I2C_SCL_NAME "/dev/m1_ddr2_i2c_scl"
#define M1_DDR2_I2C_SCL_RESET_VALUE 0
#define M1_DDR2_I2C_SCL_SPAN 16
#define M1_DDR2_I2C_SCL_TYPE "altera_avalon_pio"


/*
 * m1_ddr2_i2c_sda configuration
 *
 */

#define ALT_MODULE_CLASS_m1_ddr2_i2c_sda altera_avalon_pio
#define M1_DDR2_I2C_SDA_BASE 0x800001f0
#define M1_DDR2_I2C_SDA_BIT_CLEARING_EDGE_REGISTER 0
#define M1_DDR2_I2C_SDA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define M1_DDR2_I2C_SDA_CAPTURE 0
#define M1_DDR2_I2C_SDA_DATA_WIDTH 1
#define M1_DDR2_I2C_SDA_DO_TEST_BENCH_WIRING 0
#define M1_DDR2_I2C_SDA_DRIVEN_SIM_VALUE 0
#define M1_DDR2_I2C_SDA_EDGE_TYPE "NONE"
#define M1_DDR2_I2C_SDA_FREQ 50000000
#define M1_DDR2_I2C_SDA_HAS_IN 0
#define M1_DDR2_I2C_SDA_HAS_OUT 0
#define M1_DDR2_I2C_SDA_HAS_TRI 1
#define M1_DDR2_I2C_SDA_IRQ -1
#define M1_DDR2_I2C_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define M1_DDR2_I2C_SDA_IRQ_TYPE "NONE"
#define M1_DDR2_I2C_SDA_NAME "/dev/m1_ddr2_i2c_sda"
#define M1_DDR2_I2C_SDA_RESET_VALUE 0
#define M1_DDR2_I2C_SDA_SPAN 16
#define M1_DDR2_I2C_SDA_TYPE "altera_avalon_pio"


/*
 * m2_ddr2_i2c_scl configuration
 *
 */

#define ALT_MODULE_CLASS_m2_ddr2_i2c_scl altera_avalon_pio
#define M2_DDR2_I2C_SCL_BASE 0x80000120
#define M2_DDR2_I2C_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define M2_DDR2_I2C_SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define M2_DDR2_I2C_SCL_CAPTURE 0
#define M2_DDR2_I2C_SCL_DATA_WIDTH 1
#define M2_DDR2_I2C_SCL_DO_TEST_BENCH_WIRING 0
#define M2_DDR2_I2C_SCL_DRIVEN_SIM_VALUE 0
#define M2_DDR2_I2C_SCL_EDGE_TYPE "NONE"
#define M2_DDR2_I2C_SCL_FREQ 50000000
#define M2_DDR2_I2C_SCL_HAS_IN 0
#define M2_DDR2_I2C_SCL_HAS_OUT 1
#define M2_DDR2_I2C_SCL_HAS_TRI 0
#define M2_DDR2_I2C_SCL_IRQ -1
#define M2_DDR2_I2C_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define M2_DDR2_I2C_SCL_IRQ_TYPE "NONE"
#define M2_DDR2_I2C_SCL_NAME "/dev/m2_ddr2_i2c_scl"
#define M2_DDR2_I2C_SCL_RESET_VALUE 0
#define M2_DDR2_I2C_SCL_SPAN 16
#define M2_DDR2_I2C_SCL_TYPE "altera_avalon_pio"


/*
 * m2_ddr2_i2c_sda configuration
 *
 */

#define ALT_MODULE_CLASS_m2_ddr2_i2c_sda altera_avalon_pio
#define M2_DDR2_I2C_SDA_BASE 0x80000130
#define M2_DDR2_I2C_SDA_BIT_CLEARING_EDGE_REGISTER 0
#define M2_DDR2_I2C_SDA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define M2_DDR2_I2C_SDA_CAPTURE 0
#define M2_DDR2_I2C_SDA_DATA_WIDTH 1
#define M2_DDR2_I2C_SDA_DO_TEST_BENCH_WIRING 0
#define M2_DDR2_I2C_SDA_DRIVEN_SIM_VALUE 0
#define M2_DDR2_I2C_SDA_EDGE_TYPE "NONE"
#define M2_DDR2_I2C_SDA_FREQ 50000000
#define M2_DDR2_I2C_SDA_HAS_IN 0
#define M2_DDR2_I2C_SDA_HAS_OUT 0
#define M2_DDR2_I2C_SDA_HAS_TRI 1
#define M2_DDR2_I2C_SDA_IRQ -1
#define M2_DDR2_I2C_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define M2_DDR2_I2C_SDA_IRQ_TYPE "NONE"
#define M2_DDR2_I2C_SDA_NAME "/dev/m2_ddr2_i2c_sda"
#define M2_DDR2_I2C_SDA_RESET_VALUE 0
#define M2_DDR2_I2C_SDA_SPAN 16
#define M2_DDR2_I2C_SDA_TYPE "altera_avalon_pio"


/*
 * onchip_memory configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_BASE 0x81100000
#define ONCHIP_MEMORY_CONTENTS_INFO ""
#define ONCHIP_MEMORY_DUAL_PORT 0
#define ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE "M9K"
#define ONCHIP_MEMORY_INIT_CONTENTS_FILE "MebX_Qsys_Project_onchip_memory"
#define ONCHIP_MEMORY_INIT_MEM_CONTENT 0
#define ONCHIP_MEMORY_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY_IRQ -1
#define ONCHIP_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY_NAME "/dev/onchip_memory"
#define ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_RAM_BLOCK_TYPE "M9K"
#define ONCHIP_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_SIZE_VALUE 1024000
#define ONCHIP_MEMORY_SPAN 1024000
#define ONCHIP_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY_WRITABLE 1


/*
 * onchip_memory configuration as viewed by sgdma_rx_m_write
 *
 */

#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_BASE 0x81100000
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_CONTENTS_INFO ""
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_DUAL_PORT 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE "M9K"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_INIT_CONTENTS_FILE "MebX_Qsys_Project_onchip_memory"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_INIT_MEM_CONTENT 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_INSTANCE_ID "NONE"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_IRQ -1
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_NAME "/dev/onchip_memory"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_RAM_BLOCK_TYPE "M9K"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_SINGLE_CLOCK_OP 0
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_SIZE_VALUE 1024000
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_SPAN 1024000
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_RX_M_WRITE_ONCHIP_MEMORY_WRITABLE 1


/*
 * onchip_memory configuration as viewed by sgdma_tx_m_read
 *
 */

#define SGDMA_TX_M_READ_ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_BASE 0x81100000
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_CONTENTS_INFO ""
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_DUAL_PORT 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE "M9K"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_INIT_CONTENTS_FILE "MebX_Qsys_Project_onchip_memory"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_INIT_MEM_CONTENT 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_INSTANCE_ID "NONE"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_IRQ -1
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_NAME "/dev/onchip_memory"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_RAM_BLOCK_TYPE "M9K"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_SINGLE_CLOCK_OP 0
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_SIZE_VALUE 1024000
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_SPAN 1024000
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_TX_M_READ_ONCHIP_MEMORY_WRITABLE 1


/*
 * pio_BUTTON configuration
 *
 */

#define ALT_MODULE_CLASS_pio_BUTTON altera_avalon_pio
#define PIO_BUTTON_BASE 0x800001d0
#define PIO_BUTTON_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_BUTTON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_BUTTON_CAPTURE 0
#define PIO_BUTTON_DATA_WIDTH 4
#define PIO_BUTTON_DO_TEST_BENCH_WIRING 0
#define PIO_BUTTON_DRIVEN_SIM_VALUE 0
#define PIO_BUTTON_EDGE_TYPE "NONE"
#define PIO_BUTTON_FREQ 50000000
#define PIO_BUTTON_HAS_IN 1
#define PIO_BUTTON_HAS_OUT 0
#define PIO_BUTTON_HAS_TRI 0
#define PIO_BUTTON_IRQ -1
#define PIO_BUTTON_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_BUTTON_IRQ_TYPE "NONE"
#define PIO_BUTTON_NAME "/dev/pio_BUTTON"
#define PIO_BUTTON_RESET_VALUE 0
#define PIO_BUTTON_SPAN 16
#define PIO_BUTTON_TYPE "altera_avalon_pio"


/*
 * pio_DIP configuration
 *
 */

#define ALT_MODULE_CLASS_pio_DIP altera_avalon_pio
#define PIO_DIP_BASE 0x800001b0
#define PIO_DIP_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_DIP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_DIP_CAPTURE 0
#define PIO_DIP_DATA_WIDTH 8
#define PIO_DIP_DO_TEST_BENCH_WIRING 0
#define PIO_DIP_DRIVEN_SIM_VALUE 0
#define PIO_DIP_EDGE_TYPE "NONE"
#define PIO_DIP_FREQ 50000000
#define PIO_DIP_HAS_IN 1
#define PIO_DIP_HAS_OUT 0
#define PIO_DIP_HAS_TRI 0
#define PIO_DIP_IRQ -1
#define PIO_DIP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_DIP_IRQ_TYPE "NONE"
#define PIO_DIP_NAME "/dev/pio_DIP"
#define PIO_DIP_RESET_VALUE 0
#define PIO_DIP_SPAN 16
#define PIO_DIP_TYPE "altera_avalon_pio"


/*
 * pio_EXT configuration
 *
 */

#define ALT_MODULE_CLASS_pio_EXT altera_avalon_pio
#define PIO_EXT_BASE 0x800001a0
#define PIO_EXT_BIT_CLEARING_EDGE_REGISTER 1
#define PIO_EXT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_EXT_CAPTURE 1
#define PIO_EXT_DATA_WIDTH 1
#define PIO_EXT_DO_TEST_BENCH_WIRING 0
#define PIO_EXT_DRIVEN_SIM_VALUE 0
#define PIO_EXT_EDGE_TYPE "RISING"
#define PIO_EXT_FREQ 50000000
#define PIO_EXT_HAS_IN 1
#define PIO_EXT_HAS_OUT 0
#define PIO_EXT_HAS_TRI 0
#define PIO_EXT_IRQ 5
#define PIO_EXT_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PIO_EXT_IRQ_TYPE "LEVEL"
#define PIO_EXT_NAME "/dev/pio_EXT"
#define PIO_EXT_RESET_VALUE 0
#define PIO_EXT_SPAN 16
#define PIO_EXT_TYPE "altera_avalon_pio"


/*
 * pio_LED configuration
 *
 */

#define ALT_MODULE_CLASS_pio_LED altera_avalon_pio
#define PIO_LED_BASE 0x800001c0
#define PIO_LED_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LED_CAPTURE 0
#define PIO_LED_DATA_WIDTH 8
#define PIO_LED_DO_TEST_BENCH_WIRING 0
#define PIO_LED_DRIVEN_SIM_VALUE 0
#define PIO_LED_EDGE_TYPE "NONE"
#define PIO_LED_FREQ 50000000
#define PIO_LED_HAS_IN 0
#define PIO_LED_HAS_OUT 1
#define PIO_LED_HAS_TRI 0
#define PIO_LED_IRQ -1
#define PIO_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_LED_IRQ_TYPE "NONE"
#define PIO_LED_NAME "/dev/pio_LED"
#define PIO_LED_RESET_VALUE 0
#define PIO_LED_SPAN 16
#define PIO_LED_TYPE "altera_avalon_pio"


/*
 * pio_LED_painel configuration
 *
 */

#define ALT_MODULE_CLASS_pio_LED_painel altera_avalon_pio
#define PIO_LED_PAINEL_BASE 0x800000c0
#define PIO_LED_PAINEL_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_PAINEL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LED_PAINEL_CAPTURE 0
#define PIO_LED_PAINEL_DATA_WIDTH 21
#define PIO_LED_PAINEL_DO_TEST_BENCH_WIRING 0
#define PIO_LED_PAINEL_DRIVEN_SIM_VALUE 0
#define PIO_LED_PAINEL_EDGE_TYPE "NONE"
#define PIO_LED_PAINEL_FREQ 50000000
#define PIO_LED_PAINEL_HAS_IN 0
#define PIO_LED_PAINEL_HAS_OUT 1
#define PIO_LED_PAINEL_HAS_TRI 0
#define PIO_LED_PAINEL_IRQ -1
#define PIO_LED_PAINEL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_LED_PAINEL_IRQ_TYPE "NONE"
#define PIO_LED_PAINEL_NAME "/dev/pio_LED_painel"
#define PIO_LED_PAINEL_RESET_VALUE 0
#define PIO_LED_PAINEL_SPAN 16
#define PIO_LED_PAINEL_TYPE "altera_avalon_pio"


/*
 * pio_RST_ETH configuration
 *
 */

#define ALT_MODULE_CLASS_pio_RST_ETH altera_avalon_pio
#define PIO_RST_ETH_BASE 0x800000b0
#define PIO_RST_ETH_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_RST_ETH_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_RST_ETH_CAPTURE 0
#define PIO_RST_ETH_DATA_WIDTH 1
#define PIO_RST_ETH_DO_TEST_BENCH_WIRING 0
#define PIO_RST_ETH_DRIVEN_SIM_VALUE 0
#define PIO_RST_ETH_EDGE_TYPE "NONE"
#define PIO_RST_ETH_FREQ 50000000
#define PIO_RST_ETH_HAS_IN 0
#define PIO_RST_ETH_HAS_OUT 1
#define PIO_RST_ETH_HAS_TRI 0
#define PIO_RST_ETH_IRQ -1
#define PIO_RST_ETH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_RST_ETH_IRQ_TYPE "NONE"
#define PIO_RST_ETH_NAME "/dev/pio_RST_ETH"
#define PIO_RST_ETH_RESET_VALUE 0
#define PIO_RST_ETH_SPAN 16
#define PIO_RST_ETH_TYPE "altera_avalon_pio"


/*
 * rtcc_alarm configuration
 *
 */

#define ALT_MODULE_CLASS_rtcc_alarm altera_avalon_pio
#define RTCC_ALARM_BASE 0x800000a0
#define RTCC_ALARM_BIT_CLEARING_EDGE_REGISTER 0
#define RTCC_ALARM_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RTCC_ALARM_CAPTURE 0
#define RTCC_ALARM_DATA_WIDTH 1
#define RTCC_ALARM_DO_TEST_BENCH_WIRING 0
#define RTCC_ALARM_DRIVEN_SIM_VALUE 0
#define RTCC_ALARM_EDGE_TYPE "NONE"
#define RTCC_ALARM_FREQ 50000000
#define RTCC_ALARM_HAS_IN 1
#define RTCC_ALARM_HAS_OUT 0
#define RTCC_ALARM_HAS_TRI 0
#define RTCC_ALARM_IRQ -1
#define RTCC_ALARM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RTCC_ALARM_IRQ_TYPE "NONE"
#define RTCC_ALARM_NAME "/dev/rtcc_alarm"
#define RTCC_ALARM_RESET_VALUE 0
#define RTCC_ALARM_SPAN 16
#define RTCC_ALARM_TYPE "altera_avalon_pio"


/*
 * rtcc_cs_n configuration
 *
 */

#define ALT_MODULE_CLASS_rtcc_cs_n altera_avalon_pio
#define RTCC_CS_N_BASE 0x80000060
#define RTCC_CS_N_BIT_CLEARING_EDGE_REGISTER 0
#define RTCC_CS_N_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RTCC_CS_N_CAPTURE 0
#define RTCC_CS_N_DATA_WIDTH 1
#define RTCC_CS_N_DO_TEST_BENCH_WIRING 0
#define RTCC_CS_N_DRIVEN_SIM_VALUE 0
#define RTCC_CS_N_EDGE_TYPE "NONE"
#define RTCC_CS_N_FREQ 50000000
#define RTCC_CS_N_HAS_IN 0
#define RTCC_CS_N_HAS_OUT 1
#define RTCC_CS_N_HAS_TRI 0
#define RTCC_CS_N_IRQ -1
#define RTCC_CS_N_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RTCC_CS_N_IRQ_TYPE "NONE"
#define RTCC_CS_N_NAME "/dev/rtcc_cs_n"
#define RTCC_CS_N_RESET_VALUE 0
#define RTCC_CS_N_SPAN 16
#define RTCC_CS_N_TYPE "altera_avalon_pio"


/*
 * rtcc_sck configuration
 *
 */

#define ALT_MODULE_CLASS_rtcc_sck altera_avalon_pio
#define RTCC_SCK_BASE 0x80000070
#define RTCC_SCK_BIT_CLEARING_EDGE_REGISTER 0
#define RTCC_SCK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RTCC_SCK_CAPTURE 0
#define RTCC_SCK_DATA_WIDTH 1
#define RTCC_SCK_DO_TEST_BENCH_WIRING 0
#define RTCC_SCK_DRIVEN_SIM_VALUE 0
#define RTCC_SCK_EDGE_TYPE "NONE"
#define RTCC_SCK_FREQ 50000000
#define RTCC_SCK_HAS_IN 0
#define RTCC_SCK_HAS_OUT 1
#define RTCC_SCK_HAS_TRI 0
#define RTCC_SCK_IRQ -1
#define RTCC_SCK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RTCC_SCK_IRQ_TYPE "NONE"
#define RTCC_SCK_NAME "/dev/rtcc_sck"
#define RTCC_SCK_RESET_VALUE 0
#define RTCC_SCK_SPAN 16
#define RTCC_SCK_TYPE "altera_avalon_pio"


/*
 * rtcc_sdi configuration
 *
 */

#define ALT_MODULE_CLASS_rtcc_sdi altera_avalon_pio
#define RTCC_SDI_BASE 0x80000080
#define RTCC_SDI_BIT_CLEARING_EDGE_REGISTER 0
#define RTCC_SDI_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RTCC_SDI_CAPTURE 0
#define RTCC_SDI_DATA_WIDTH 1
#define RTCC_SDI_DO_TEST_BENCH_WIRING 0
#define RTCC_SDI_DRIVEN_SIM_VALUE 0
#define RTCC_SDI_EDGE_TYPE "NONE"
#define RTCC_SDI_FREQ 50000000
#define RTCC_SDI_HAS_IN 0
#define RTCC_SDI_HAS_OUT 1
#define RTCC_SDI_HAS_TRI 0
#define RTCC_SDI_IRQ -1
#define RTCC_SDI_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RTCC_SDI_IRQ_TYPE "NONE"
#define RTCC_SDI_NAME "/dev/rtcc_sdi"
#define RTCC_SDI_RESET_VALUE 0
#define RTCC_SDI_SPAN 16
#define RTCC_SDI_TYPE "altera_avalon_pio"


/*
 * rtcc_sdo configuration
 *
 */

#define ALT_MODULE_CLASS_rtcc_sdo altera_avalon_pio
#define RTCC_SDO_BASE 0x80000090
#define RTCC_SDO_BIT_CLEARING_EDGE_REGISTER 0
#define RTCC_SDO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RTCC_SDO_CAPTURE 0
#define RTCC_SDO_DATA_WIDTH 1
#define RTCC_SDO_DO_TEST_BENCH_WIRING 0
#define RTCC_SDO_DRIVEN_SIM_VALUE 0
#define RTCC_SDO_EDGE_TYPE "NONE"
#define RTCC_SDO_FREQ 50000000
#define RTCC_SDO_HAS_IN 1
#define RTCC_SDO_HAS_OUT 0
#define RTCC_SDO_HAS_TRI 0
#define RTCC_SDO_IRQ -1
#define RTCC_SDO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RTCC_SDO_IRQ_TYPE "NONE"
#define RTCC_SDO_NAME "/dev/rtcc_sdo"
#define RTCC_SDO_RESET_VALUE 0
#define RTCC_SDO_SPAN 16
#define RTCC_SDO_TYPE "altera_avalon_pio"


/*
 * sd_clk configuration
 *
 */

#define ALT_MODULE_CLASS_sd_clk altera_avalon_pio
#define SD_CLK_BASE 0x80000160
#define SD_CLK_BIT_CLEARING_EDGE_REGISTER 0
#define SD_CLK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SD_CLK_CAPTURE 0
#define SD_CLK_DATA_WIDTH 1
#define SD_CLK_DO_TEST_BENCH_WIRING 0
#define SD_CLK_DRIVEN_SIM_VALUE 0
#define SD_CLK_EDGE_TYPE "NONE"
#define SD_CLK_FREQ 50000000
#define SD_CLK_HAS_IN 0
#define SD_CLK_HAS_OUT 1
#define SD_CLK_HAS_TRI 0
#define SD_CLK_IRQ -1
#define SD_CLK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SD_CLK_IRQ_TYPE "NONE"
#define SD_CLK_NAME "/dev/sd_clk"
#define SD_CLK_RESET_VALUE 0
#define SD_CLK_SPAN 16
#define SD_CLK_TYPE "altera_avalon_pio"


/*
 * sd_cmd configuration
 *
 */

#define ALT_MODULE_CLASS_sd_cmd altera_avalon_pio
#define SD_CMD_BASE 0x80000170
#define SD_CMD_BIT_CLEARING_EDGE_REGISTER 0
#define SD_CMD_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SD_CMD_CAPTURE 0
#define SD_CMD_DATA_WIDTH 1
#define SD_CMD_DO_TEST_BENCH_WIRING 0
#define SD_CMD_DRIVEN_SIM_VALUE 0
#define SD_CMD_EDGE_TYPE "NONE"
#define SD_CMD_FREQ 50000000
#define SD_CMD_HAS_IN 0
#define SD_CMD_HAS_OUT 0
#define SD_CMD_HAS_TRI 1
#define SD_CMD_IRQ -1
#define SD_CMD_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SD_CMD_IRQ_TYPE "NONE"
#define SD_CMD_NAME "/dev/sd_cmd"
#define SD_CMD_RESET_VALUE 0
#define SD_CMD_SPAN 16
#define SD_CMD_TYPE "altera_avalon_pio"


/*
 * sd_dat configuration
 *
 */

#define ALT_MODULE_CLASS_sd_dat altera_avalon_pio
#define SD_DAT_BASE 0x80000180
#define SD_DAT_BIT_CLEARING_EDGE_REGISTER 0
#define SD_DAT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SD_DAT_CAPTURE 0
#define SD_DAT_DATA_WIDTH 4
#define SD_DAT_DO_TEST_BENCH_WIRING 0
#define SD_DAT_DRIVEN_SIM_VALUE 0
#define SD_DAT_EDGE_TYPE "NONE"
#define SD_DAT_FREQ 50000000
#define SD_DAT_HAS_IN 0
#define SD_DAT_HAS_OUT 0
#define SD_DAT_HAS_TRI 1
#define SD_DAT_IRQ -1
#define SD_DAT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SD_DAT_IRQ_TYPE "NONE"
#define SD_DAT_NAME "/dev/sd_dat"
#define SD_DAT_RESET_VALUE 0
#define SD_DAT_SPAN 16
#define SD_DAT_TYPE "altera_avalon_pio"


/*
 * sd_wp_n configuration
 *
 */

#define ALT_MODULE_CLASS_sd_wp_n altera_avalon_pio
#define SD_WP_N_BASE 0x80000190
#define SD_WP_N_BIT_CLEARING_EDGE_REGISTER 0
#define SD_WP_N_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SD_WP_N_CAPTURE 0
#define SD_WP_N_DATA_WIDTH 1
#define SD_WP_N_DO_TEST_BENCH_WIRING 0
#define SD_WP_N_DRIVEN_SIM_VALUE 0
#define SD_WP_N_EDGE_TYPE "NONE"
#define SD_WP_N_FREQ 50000000
#define SD_WP_N_HAS_IN 1
#define SD_WP_N_HAS_OUT 0
#define SD_WP_N_HAS_TRI 0
#define SD_WP_N_IRQ -1
#define SD_WP_N_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SD_WP_N_IRQ_TYPE "NONE"
#define SD_WP_N_NAME "/dev/sd_wp_n"
#define SD_WP_N_RESET_VALUE 0
#define SD_WP_N_SPAN 16
#define SD_WP_N_TYPE "altera_avalon_pio"


/*
 * sgdma_rx configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_rx altera_avalon_sgdma
#define SGDMA_RX_ADDRESS_WIDTH 32
#define SGDMA_RX_ALWAYS_DO_MAX_BURST 1
#define SGDMA_RX_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_RX_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_RX_BASE 0x81204000
#define SGDMA_RX_BURST_DATA_WIDTH 8
#define SGDMA_RX_BURST_TRANSFER 0
#define SGDMA_RX_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_RX_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_RX_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_RX_CONTROL_DATA_WIDTH 8
#define SGDMA_RX_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_RX_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_RX_DESCRIPTOR_READ_BURST 0
#define SGDMA_RX_DESC_DATA_WIDTH 32
#define SGDMA_RX_HAS_READ_BLOCK 0
#define SGDMA_RX_HAS_WRITE_BLOCK 1
#define SGDMA_RX_IN_ERROR_WIDTH 0
#define SGDMA_RX_IRQ 1
#define SGDMA_RX_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_RX_NAME "/dev/sgdma_rx"
#define SGDMA_RX_OUT_ERROR_WIDTH 0
#define SGDMA_RX_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_RX_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_RX_SPAN 64
#define SGDMA_RX_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_RX_STREAM_DATA_WIDTH 32
#define SGDMA_RX_SYMBOLS_PER_BEAT 4
#define SGDMA_RX_TYPE "altera_avalon_sgdma"
#define SGDMA_RX_UNALIGNED_TRANSFER 0
#define SGDMA_RX_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_RX_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_tx configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_tx altera_avalon_sgdma
#define SGDMA_TX_ADDRESS_WIDTH 32
#define SGDMA_TX_ALWAYS_DO_MAX_BURST 1
#define SGDMA_TX_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_TX_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_TX_BASE 0x81204040
#define SGDMA_TX_BURST_DATA_WIDTH 8
#define SGDMA_TX_BURST_TRANSFER 0
#define SGDMA_TX_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_TX_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_TX_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_TX_CONTROL_DATA_WIDTH 8
#define SGDMA_TX_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_TX_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_TX_DESCRIPTOR_READ_BURST 0
#define SGDMA_TX_DESC_DATA_WIDTH 32
#define SGDMA_TX_HAS_READ_BLOCK 1
#define SGDMA_TX_HAS_WRITE_BLOCK 0
#define SGDMA_TX_IN_ERROR_WIDTH 0
#define SGDMA_TX_IRQ 0
#define SGDMA_TX_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_TX_NAME "/dev/sgdma_tx"
#define SGDMA_TX_OUT_ERROR_WIDTH 0
#define SGDMA_TX_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_TX_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_TX_SPAN 64
#define SGDMA_TX_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_TX_STREAM_DATA_WIDTH 32
#define SGDMA_TX_SYMBOLS_PER_BEAT 4
#define SGDMA_TX_TYPE "altera_avalon_sgdma"
#define SGDMA_TX_UNALIGNED_TRANSFER 0
#define SGDMA_TX_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_TX_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sinc_in configuration
 *
 */

#define ALT_MODULE_CLASS_sinc_in altera_avalon_pio
#define SINC_IN_BASE 0x80000040
#define SINC_IN_BIT_CLEARING_EDGE_REGISTER 0
#define SINC_IN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SINC_IN_CAPTURE 0
#define SINC_IN_DATA_WIDTH 1
#define SINC_IN_DO_TEST_BENCH_WIRING 0
#define SINC_IN_DRIVEN_SIM_VALUE 0
#define SINC_IN_EDGE_TYPE "NONE"
#define SINC_IN_FREQ 50000000
#define SINC_IN_HAS_IN 1
#define SINC_IN_HAS_OUT 0
#define SINC_IN_HAS_TRI 0
#define SINC_IN_IRQ -1
#define SINC_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SINC_IN_IRQ_TYPE "NONE"
#define SINC_IN_NAME "/dev/sinc_in"
#define SINC_IN_RESET_VALUE 0
#define SINC_IN_SPAN 16
#define SINC_IN_TYPE "altera_avalon_pio"


/*
 * sinc_out configuration
 *
 */

#define ALT_MODULE_CLASS_sinc_out altera_avalon_pio
#define SINC_OUT_BASE 0x80000050
#define SINC_OUT_BIT_CLEARING_EDGE_REGISTER 0
#define SINC_OUT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SINC_OUT_CAPTURE 0
#define SINC_OUT_DATA_WIDTH 1
#define SINC_OUT_DO_TEST_BENCH_WIRING 0
#define SINC_OUT_DRIVEN_SIM_VALUE 0
#define SINC_OUT_EDGE_TYPE "NONE"
#define SINC_OUT_FREQ 50000000
#define SINC_OUT_HAS_IN 0
#define SINC_OUT_HAS_OUT 1
#define SINC_OUT_HAS_TRI 0
#define SINC_OUT_IRQ -1
#define SINC_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SINC_OUT_IRQ_TYPE "NONE"
#define SINC_OUT_NAME "/dev/sinc_out"
#define SINC_OUT_RESET_VALUE 0
#define SINC_OUT_SPAN 16
#define SINC_OUT_TYPE "altera_avalon_pio"


/*
 * sysid_qsys configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys altera_avalon_sysid_qsys
#define SYSID_QSYS_BASE 0x812040c0
#define SYSID_QSYS_ID 0
#define SYSID_QSYS_IRQ -1
#define SYSID_QSYS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_NAME "/dev/sysid_qsys"
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_TIMESTAMP 1525198004
#define SYSID_QSYS_TYPE "altera_avalon_sysid_qsys"


/*
 * temp_scl configuration
 *
 */

#define ALT_MODULE_CLASS_temp_scl altera_avalon_pio
#define TEMP_SCL_BASE 0x80000150
#define TEMP_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP_SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP_SCL_CAPTURE 0
#define TEMP_SCL_DATA_WIDTH 1
#define TEMP_SCL_DO_TEST_BENCH_WIRING 0
#define TEMP_SCL_DRIVEN_SIM_VALUE 0
#define TEMP_SCL_EDGE_TYPE "NONE"
#define TEMP_SCL_FREQ 50000000
#define TEMP_SCL_HAS_IN 0
#define TEMP_SCL_HAS_OUT 1
#define TEMP_SCL_HAS_TRI 0
#define TEMP_SCL_IRQ -1
#define TEMP_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TEMP_SCL_IRQ_TYPE "NONE"
#define TEMP_SCL_NAME "/dev/temp_scl"
#define TEMP_SCL_RESET_VALUE 0
#define TEMP_SCL_SPAN 16
#define TEMP_SCL_TYPE "altera_avalon_pio"


/*
 * temp_sda configuration
 *
 */

#define ALT_MODULE_CLASS_temp_sda altera_avalon_pio
#define TEMP_SDA_BASE 0x80000140
#define TEMP_SDA_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP_SDA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP_SDA_CAPTURE 0
#define TEMP_SDA_DATA_WIDTH 1
#define TEMP_SDA_DO_TEST_BENCH_WIRING 0
#define TEMP_SDA_DRIVEN_SIM_VALUE 0
#define TEMP_SDA_EDGE_TYPE "NONE"
#define TEMP_SDA_FREQ 50000000
#define TEMP_SDA_HAS_IN 0
#define TEMP_SDA_HAS_OUT 0
#define TEMP_SDA_HAS_TRI 1
#define TEMP_SDA_IRQ -1
#define TEMP_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TEMP_SDA_IRQ_TYPE "NONE"
#define TEMP_SDA_NAME "/dev/temp_sda"
#define TEMP_SDA_RESET_VALUE 0
#define TEMP_SDA_SPAN 16
#define TEMP_SDA_TYPE "altera_avalon_pio"


/*
 * timer_1ms configuration
 *
 */

#define ALT_MODULE_CLASS_timer_1ms altera_avalon_timer
#define TIMER_1MS_ALWAYS_RUN 1
#define TIMER_1MS_BASE 0x80000020
#define TIMER_1MS_COUNTER_SIZE 32
#define TIMER_1MS_FIXED_PERIOD 0
#define TIMER_1MS_FREQ 50000000
#define TIMER_1MS_IRQ 3
#define TIMER_1MS_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_1MS_LOAD_VALUE 49999
#define TIMER_1MS_MULT 0.001
#define TIMER_1MS_NAME "/dev/timer_1ms"
#define TIMER_1MS_PERIOD 1
#define TIMER_1MS_PERIOD_UNITS "ms"
#define TIMER_1MS_RESET_OUTPUT 0
#define TIMER_1MS_SNAPSHOT 1
#define TIMER_1MS_SPAN 32
#define TIMER_1MS_TICKS_PER_SEC 1000
#define TIMER_1MS_TIMEOUT_PULSE_OUTPUT 1
#define TIMER_1MS_TYPE "altera_avalon_timer"


/*
 * timer_1us configuration
 *
 */

#define ALT_MODULE_CLASS_timer_1us altera_avalon_timer
#define TIMER_1US_ALWAYS_RUN 1
#define TIMER_1US_BASE 0x80000000
#define TIMER_1US_COUNTER_SIZE 32
#define TIMER_1US_FIXED_PERIOD 0
#define TIMER_1US_FREQ 50000000
#define TIMER_1US_IRQ 4
#define TIMER_1US_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_1US_LOAD_VALUE 49
#define TIMER_1US_MULT 1.0E-6
#define TIMER_1US_NAME "/dev/timer_1us"
#define TIMER_1US_PERIOD 1
#define TIMER_1US_PERIOD_UNITS "us"
#define TIMER_1US_RESET_OUTPUT 0
#define TIMER_1US_SNAPSHOT 1
#define TIMER_1US_SPAN 32
#define TIMER_1US_TICKS_PER_SEC 1000000
#define TIMER_1US_TIMEOUT_PULSE_OUTPUT 1
#define TIMER_1US_TYPE "altera_avalon_timer"


/*
 * tse_mac configuration
 *
 */

#define ALT_MODULE_CLASS_tse_mac altera_eth_tse
#define TSE_MAC_BASE 0x81203800
#define TSE_MAC_ENABLE_MACLITE 0
#define TSE_MAC_FIFO_WIDTH 32
#define TSE_MAC_IRQ -1
#define TSE_MAC_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TSE_MAC_IS_MULTICHANNEL_MAC 0
#define TSE_MAC_MACLITE_GIGE 0
#define TSE_MAC_MDIO_SHARED 0
#define TSE_MAC_NAME "/dev/tse_mac"
#define TSE_MAC_NUMBER_OF_CHANNEL 1
#define TSE_MAC_NUMBER_OF_MAC_MDIO_SHARED 1
#define TSE_MAC_PCS 1
#define TSE_MAC_PCS_ID 3
#define TSE_MAC_PCS_SGMII 1
#define TSE_MAC_RECEIVE_FIFO_DEPTH 2048
#define TSE_MAC_REGISTER_SHARED 0
#define TSE_MAC_RGMII 0
#define TSE_MAC_SPAN 1024
#define TSE_MAC_TRANSMIT_FIFO_DEPTH 2048
#define TSE_MAC_TYPE "altera_eth_tse"
#define TSE_MAC_USE_MDIO 1


/*
 * ucosii configuration
 *
 */

#define OS_ARG_CHK_EN 1
#define OS_CPU_HOOKS_EN 1
#define OS_DEBUG_EN 1
#define OS_EVENT_NAME_SIZE 32
#define OS_FLAGS_NBITS 16
#define OS_FLAG_ACCEPT_EN 1
#define OS_FLAG_DEL_EN 1
#define OS_FLAG_EN 1
#define OS_FLAG_NAME_SIZE 32
#define OS_FLAG_QUERY_EN 1
#define OS_FLAG_WAIT_CLR_EN 1
#define OS_LOWEST_PRIO 60
#define OS_MAX_EVENTS 120
#define OS_MAX_FLAGS 20
#define OS_MAX_MEM_PART 60
#define OS_MAX_QS 20
#define OS_MAX_TASKS 20
#define OS_MBOX_ACCEPT_EN 1
#define OS_MBOX_DEL_EN 1
#define OS_MBOX_EN 1
#define OS_MBOX_POST_EN 1
#define OS_MBOX_POST_OPT_EN 1
#define OS_MBOX_QUERY_EN 1
#define OS_MEM_EN 1
#define OS_MEM_NAME_SIZE 32
#define OS_MEM_QUERY_EN 1
#define OS_MUTEX_ACCEPT_EN 1
#define OS_MUTEX_DEL_EN 1
#define OS_MUTEX_EN 1
#define OS_MUTEX_QUERY_EN 1
#define OS_Q_ACCEPT_EN 1
#define OS_Q_DEL_EN 1
#define OS_Q_EN 1
#define OS_Q_FLUSH_EN 1
#define OS_Q_POST_EN 1
#define OS_Q_POST_FRONT_EN 1
#define OS_Q_POST_OPT_EN 1
#define OS_Q_QUERY_EN 1
#define OS_SCHED_LOCK_EN 1
#define OS_SEM_ACCEPT_EN 1
#define OS_SEM_DEL_EN 1
#define OS_SEM_EN 1
#define OS_SEM_QUERY_EN 1
#define OS_SEM_SET_EN 1
#define OS_TASK_CHANGE_PRIO_EN 1
#define OS_TASK_CREATE_EN 1
#define OS_TASK_CREATE_EXT_EN 1
#define OS_TASK_DEL_EN 1
#define OS_TASK_IDLE_STK_SIZE 512
#define OS_TASK_NAME_SIZE 32
#define OS_TASK_PROFILE_EN 1
#define OS_TASK_QUERY_EN 1
#define OS_TASK_STAT_EN 1
#define OS_TASK_STAT_STK_CHK_EN 1
#define OS_TASK_STAT_STK_SIZE 512
#define OS_TASK_SUSPEND_EN 1
#define OS_TASK_SW_HOOK_EN 1
#define OS_TASK_TMR_PRIO 0
#define OS_TASK_TMR_STK_SIZE 512
#define OS_THREAD_SAFE_NEWLIB 1
#define OS_TICKS_PER_SEC TIMER_1MS_TICKS_PER_SEC
#define OS_TICK_STEP_EN 1
#define OS_TIME_DLY_HMSM_EN 1
#define OS_TIME_DLY_RESUME_EN 1
#define OS_TIME_GET_SET_EN 1
#define OS_TIME_TICK_HOOK_EN 1
#define OS_TMR_CFG_MAX 16
#define OS_TMR_CFG_NAME_SIZE 16
#define OS_TMR_CFG_TICKS_PER_SEC 10
#define OS_TMR_CFG_WHEEL_SIZE 2
#define OS_TMR_EN 0

#endif /* __SYSTEM_H_ */
