	MebX_Qsys_Project u0 (
		.button_export                                        (<connected-to-button_export>),                                        //                            button.export
		.clk50_clk                                            (<connected-to-clk50_clk>),                                            //                             clk50.clk
		.comm_a_conduit_end_spw_si_signal                     (<connected-to-comm_a_conduit_end_spw_si_signal>),                     //                comm_a_conduit_end.spw_si_signal
		.comm_a_conduit_end_spw_di_signal                     (<connected-to-comm_a_conduit_end_spw_di_signal>),                     //                                  .spw_di_signal
		.comm_a_conduit_end_spw_do_signal                     (<connected-to-comm_a_conduit_end_spw_do_signal>),                     //                                  .spw_do_signal
		.comm_a_conduit_end_spw_so_signal                     (<connected-to-comm_a_conduit_end_spw_so_signal>),                     //                                  .spw_so_signal
		.comm_b_conduit_end_spw_si_signal                     (<connected-to-comm_b_conduit_end_spw_si_signal>),                     //                comm_b_conduit_end.spw_si_signal
		.comm_b_conduit_end_spw_di_signal                     (<connected-to-comm_b_conduit_end_spw_di_signal>),                     //                                  .spw_di_signal
		.comm_b_conduit_end_spw_do_signal                     (<connected-to-comm_b_conduit_end_spw_do_signal>),                     //                                  .spw_do_signal
		.comm_b_conduit_end_spw_so_signal                     (<connected-to-comm_b_conduit_end_spw_so_signal>),                     //                                  .spw_so_signal
		.comm_c_conduit_end_spw_si_signal                     (<connected-to-comm_c_conduit_end_spw_si_signal>),                     //                comm_c_conduit_end.spw_si_signal
		.comm_c_conduit_end_spw_di_signal                     (<connected-to-comm_c_conduit_end_spw_di_signal>),                     //                                  .spw_di_signal
		.comm_c_conduit_end_spw_do_signal                     (<connected-to-comm_c_conduit_end_spw_do_signal>),                     //                                  .spw_do_signal
		.comm_c_conduit_end_spw_so_signal                     (<connected-to-comm_c_conduit_end_spw_so_signal>),                     //                                  .spw_so_signal
		.comm_d_conduit_end_spw_si_signal                     (<connected-to-comm_d_conduit_end_spw_si_signal>),                     //                comm_d_conduit_end.spw_si_signal
		.comm_d_conduit_end_spw_di_signal                     (<connected-to-comm_d_conduit_end_spw_di_signal>),                     //                                  .spw_di_signal
		.comm_d_conduit_end_spw_do_signal                     (<connected-to-comm_d_conduit_end_spw_do_signal>),                     //                                  .spw_do_signal
		.comm_d_conduit_end_spw_so_signal                     (<connected-to-comm_d_conduit_end_spw_so_signal>),                     //                                  .spw_so_signal
		.comm_e_conduit_end_spw_si_signal                     (<connected-to-comm_e_conduit_end_spw_si_signal>),                     //                comm_e_conduit_end.spw_si_signal
		.comm_e_conduit_end_spw_di_signal                     (<connected-to-comm_e_conduit_end_spw_di_signal>),                     //                                  .spw_di_signal
		.comm_e_conduit_end_spw_do_signal                     (<connected-to-comm_e_conduit_end_spw_do_signal>),                     //                                  .spw_do_signal
		.comm_e_conduit_end_spw_so_signal                     (<connected-to-comm_e_conduit_end_spw_so_signal>),                     //                                  .spw_so_signal
		.comm_f_conduit_end_spw_si_signal                     (<connected-to-comm_f_conduit_end_spw_si_signal>),                     //                comm_f_conduit_end.spw_si_signal
		.comm_f_conduit_end_spw_di_signal                     (<connected-to-comm_f_conduit_end_spw_di_signal>),                     //                                  .spw_di_signal
		.comm_f_conduit_end_spw_do_signal                     (<connected-to-comm_f_conduit_end_spw_do_signal>),                     //                                  .spw_do_signal
		.comm_f_conduit_end_spw_so_signal                     (<connected-to-comm_f_conduit_end_spw_so_signal>),                     //                                  .spw_so_signal
		.comm_g_conduit_end_spw_si_signal                     (<connected-to-comm_g_conduit_end_spw_si_signal>),                     //                comm_g_conduit_end.spw_si_signal
		.comm_g_conduit_end_spw_di_signal                     (<connected-to-comm_g_conduit_end_spw_di_signal>),                     //                                  .spw_di_signal
		.comm_g_conduit_end_spw_do_signal                     (<connected-to-comm_g_conduit_end_spw_do_signal>),                     //                                  .spw_do_signal
		.comm_g_conduit_end_spw_so_signal                     (<connected-to-comm_g_conduit_end_spw_so_signal>),                     //                                  .spw_so_signal
		.comm_h_conduit_end_spw_si_signal                     (<connected-to-comm_h_conduit_end_spw_si_signal>),                     //                comm_h_conduit_end.spw_si_signal
		.comm_h_conduit_end_spw_di_signal                     (<connected-to-comm_h_conduit_end_spw_di_signal>),                     //                                  .spw_di_signal
		.comm_h_conduit_end_spw_do_signal                     (<connected-to-comm_h_conduit_end_spw_do_signal>),                     //                                  .spw_do_signal
		.comm_h_conduit_end_spw_so_signal                     (<connected-to-comm_h_conduit_end_spw_so_signal>),                     //                                  .spw_so_signal
		.csense_adc_fo_export                                 (<connected-to-csense_adc_fo_export>),                                 //                     csense_adc_fo.export
		.csense_cs_n_export                                   (<connected-to-csense_cs_n_export>),                                   //                       csense_cs_n.export
		.csense_sck_export                                    (<connected-to-csense_sck_export>),                                    //                        csense_sck.export
		.csense_sdi_export                                    (<connected-to-csense_sdi_export>),                                    //                        csense_sdi.export
		.csense_sdo_export                                    (<connected-to-csense_sdo_export>),                                    //                        csense_sdo.export
		.dip_export                                           (<connected-to-dip_export>),                                           //                               dip.export
		.eth_rst_export                                       (<connected-to-eth_rst_export>),                                       //                           eth_rst.export
		.ext_export                                           (<connected-to-ext_export>),                                           //                               ext.export
		.led_de4_export                                       (<connected-to-led_de4_export>),                                       //                           led_de4.export
		.led_painel_export                                    (<connected-to-led_painel_export>),                                    //                        led_painel.export
		.m1_ddr2_i2c_scl_export                               (<connected-to-m1_ddr2_i2c_scl_export>),                               //                   m1_ddr2_i2c_scl.export
		.m1_ddr2_i2c_sda_export                               (<connected-to-m1_ddr2_i2c_sda_export>),                               //                   m1_ddr2_i2c_sda.export
		.m1_ddr2_memory_mem_a                                 (<connected-to-m1_ddr2_memory_mem_a>),                                 //                    m1_ddr2_memory.mem_a
		.m1_ddr2_memory_mem_ba                                (<connected-to-m1_ddr2_memory_mem_ba>),                                //                                  .mem_ba
		.m1_ddr2_memory_mem_ck                                (<connected-to-m1_ddr2_memory_mem_ck>),                                //                                  .mem_ck
		.m1_ddr2_memory_mem_ck_n                              (<connected-to-m1_ddr2_memory_mem_ck_n>),                              //                                  .mem_ck_n
		.m1_ddr2_memory_mem_cke                               (<connected-to-m1_ddr2_memory_mem_cke>),                               //                                  .mem_cke
		.m1_ddr2_memory_mem_cs_n                              (<connected-to-m1_ddr2_memory_mem_cs_n>),                              //                                  .mem_cs_n
		.m1_ddr2_memory_mem_dm                                (<connected-to-m1_ddr2_memory_mem_dm>),                                //                                  .mem_dm
		.m1_ddr2_memory_mem_ras_n                             (<connected-to-m1_ddr2_memory_mem_ras_n>),                             //                                  .mem_ras_n
		.m1_ddr2_memory_mem_cas_n                             (<connected-to-m1_ddr2_memory_mem_cas_n>),                             //                                  .mem_cas_n
		.m1_ddr2_memory_mem_we_n                              (<connected-to-m1_ddr2_memory_mem_we_n>),                              //                                  .mem_we_n
		.m1_ddr2_memory_mem_dq                                (<connected-to-m1_ddr2_memory_mem_dq>),                                //                                  .mem_dq
		.m1_ddr2_memory_mem_dqs                               (<connected-to-m1_ddr2_memory_mem_dqs>),                               //                                  .mem_dqs
		.m1_ddr2_memory_mem_dqs_n                             (<connected-to-m1_ddr2_memory_mem_dqs_n>),                             //                                  .mem_dqs_n
		.m1_ddr2_memory_mem_odt                               (<connected-to-m1_ddr2_memory_mem_odt>),                               //                                  .mem_odt
		.m1_ddr2_memory_pll_ref_clk_clk                       (<connected-to-m1_ddr2_memory_pll_ref_clk_clk>),                       //        m1_ddr2_memory_pll_ref_clk.clk
		.m1_ddr2_memory_status_local_init_done                (<connected-to-m1_ddr2_memory_status_local_init_done>),                //             m1_ddr2_memory_status.local_init_done
		.m1_ddr2_memory_status_local_cal_success              (<connected-to-m1_ddr2_memory_status_local_cal_success>),              //                                  .local_cal_success
		.m1_ddr2_memory_status_local_cal_fail                 (<connected-to-m1_ddr2_memory_status_local_cal_fail>),                 //                                  .local_cal_fail
		.m1_ddr2_oct_rdn                                      (<connected-to-m1_ddr2_oct_rdn>),                                      //                       m1_ddr2_oct.rdn
		.m1_ddr2_oct_rup                                      (<connected-to-m1_ddr2_oct_rup>),                                      //                                  .rup
		.m2_ddr2_i2c_scl_export                               (<connected-to-m2_ddr2_i2c_scl_export>),                               //                   m2_ddr2_i2c_scl.export
		.m2_ddr2_i2c_sda_export                               (<connected-to-m2_ddr2_i2c_sda_export>),                               //                   m2_ddr2_i2c_sda.export
		.m2_ddr2_memory_mem_a                                 (<connected-to-m2_ddr2_memory_mem_a>),                                 //                    m2_ddr2_memory.mem_a
		.m2_ddr2_memory_mem_ba                                (<connected-to-m2_ddr2_memory_mem_ba>),                                //                                  .mem_ba
		.m2_ddr2_memory_mem_ck                                (<connected-to-m2_ddr2_memory_mem_ck>),                                //                                  .mem_ck
		.m2_ddr2_memory_mem_ck_n                              (<connected-to-m2_ddr2_memory_mem_ck_n>),                              //                                  .mem_ck_n
		.m2_ddr2_memory_mem_cke                               (<connected-to-m2_ddr2_memory_mem_cke>),                               //                                  .mem_cke
		.m2_ddr2_memory_mem_cs_n                              (<connected-to-m2_ddr2_memory_mem_cs_n>),                              //                                  .mem_cs_n
		.m2_ddr2_memory_mem_dm                                (<connected-to-m2_ddr2_memory_mem_dm>),                                //                                  .mem_dm
		.m2_ddr2_memory_mem_ras_n                             (<connected-to-m2_ddr2_memory_mem_ras_n>),                             //                                  .mem_ras_n
		.m2_ddr2_memory_mem_cas_n                             (<connected-to-m2_ddr2_memory_mem_cas_n>),                             //                                  .mem_cas_n
		.m2_ddr2_memory_mem_we_n                              (<connected-to-m2_ddr2_memory_mem_we_n>),                              //                                  .mem_we_n
		.m2_ddr2_memory_mem_dq                                (<connected-to-m2_ddr2_memory_mem_dq>),                                //                                  .mem_dq
		.m2_ddr2_memory_mem_dqs                               (<connected-to-m2_ddr2_memory_mem_dqs>),                               //                                  .mem_dqs
		.m2_ddr2_memory_mem_dqs_n                             (<connected-to-m2_ddr2_memory_mem_dqs_n>),                             //                                  .mem_dqs_n
		.m2_ddr2_memory_mem_odt                               (<connected-to-m2_ddr2_memory_mem_odt>),                               //                                  .mem_odt
		.m2_ddr2_memory_dll_sharing_dll_pll_locked            (<connected-to-m2_ddr2_memory_dll_sharing_dll_pll_locked>),            //        m2_ddr2_memory_dll_sharing.dll_pll_locked
		.m2_ddr2_memory_dll_sharing_dll_delayctrl             (<connected-to-m2_ddr2_memory_dll_sharing_dll_delayctrl>),             //                                  .dll_delayctrl
		.m2_ddr2_memory_pll_sharing_pll_mem_clk               (<connected-to-m2_ddr2_memory_pll_sharing_pll_mem_clk>),               //        m2_ddr2_memory_pll_sharing.pll_mem_clk
		.m2_ddr2_memory_pll_sharing_pll_write_clk             (<connected-to-m2_ddr2_memory_pll_sharing_pll_write_clk>),             //                                  .pll_write_clk
		.m2_ddr2_memory_pll_sharing_pll_locked                (<connected-to-m2_ddr2_memory_pll_sharing_pll_locked>),                //                                  .pll_locked
		.m2_ddr2_memory_pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-m2_ddr2_memory_pll_sharing_pll_write_clk_pre_phy_clk>), //                                  .pll_write_clk_pre_phy_clk
		.m2_ddr2_memory_pll_sharing_pll_addr_cmd_clk          (<connected-to-m2_ddr2_memory_pll_sharing_pll_addr_cmd_clk>),          //                                  .pll_addr_cmd_clk
		.m2_ddr2_memory_pll_sharing_pll_avl_clk               (<connected-to-m2_ddr2_memory_pll_sharing_pll_avl_clk>),               //                                  .pll_avl_clk
		.m2_ddr2_memory_pll_sharing_pll_config_clk            (<connected-to-m2_ddr2_memory_pll_sharing_pll_config_clk>),            //                                  .pll_config_clk
		.m2_ddr2_memory_status_local_init_done                (<connected-to-m2_ddr2_memory_status_local_init_done>),                //             m2_ddr2_memory_status.local_init_done
		.m2_ddr2_memory_status_local_cal_success              (<connected-to-m2_ddr2_memory_status_local_cal_success>),              //                                  .local_cal_success
		.m2_ddr2_memory_status_local_cal_fail                 (<connected-to-m2_ddr2_memory_status_local_cal_fail>),                 //                                  .local_cal_fail
		.m2_ddr2_oct_rdn                                      (<connected-to-m2_ddr2_oct_rdn>),                                      //                       m2_ddr2_oct.rdn
		.m2_ddr2_oct_rup                                      (<connected-to-m2_ddr2_oct_rup>),                                      //                                  .rup
		.rst_reset_n                                          (<connected-to-rst_reset_n>),                                          //                               rst.reset_n
		.rtcc_alarm_export                                    (<connected-to-rtcc_alarm_export>),                                    //                        rtcc_alarm.export
		.rtcc_cs_n_export                                     (<connected-to-rtcc_cs_n_export>),                                     //                         rtcc_cs_n.export
		.rtcc_sck_export                                      (<connected-to-rtcc_sck_export>),                                      //                          rtcc_sck.export
		.rtcc_sdi_export                                      (<connected-to-rtcc_sdi_export>),                                      //                          rtcc_sdi.export
		.rtcc_sdo_export                                      (<connected-to-rtcc_sdo_export>),                                      //                          rtcc_sdo.export
		.sd_clk_export                                        (<connected-to-sd_clk_export>),                                        //                            sd_clk.export
		.sd_cmd_export                                        (<connected-to-sd_cmd_export>),                                        //                            sd_cmd.export
		.sd_dat_export                                        (<connected-to-sd_dat_export>),                                        //                            sd_dat.export
		.sd_wp_n_export                                       (<connected-to-sd_wp_n_export>),                                       //                           sd_wp_n.export
		.sinc_in_export                                       (<connected-to-sinc_in_export>),                                       //                           sinc_in.export
		.sinc_out_export                                      (<connected-to-sinc_out_export>),                                      //                          sinc_out.export
		.ssdp_ssdp0                                           (<connected-to-ssdp_ssdp0>),                                           //                              ssdp.ssdp0
		.ssdp_ssdp1                                           (<connected-to-ssdp_ssdp1>),                                           //                                  .ssdp1
		.temp_scl_export                                      (<connected-to-temp_scl_export>),                                      //                          temp_scl.export
		.temp_sda_export                                      (<connected-to-temp_sda_export>),                                      //                          temp_sda.export
		.timer_1ms_external_port_export                       (<connected-to-timer_1ms_external_port_export>),                       //           timer_1ms_external_port.export
		.timer_1us_external_port_export                       (<connected-to-timer_1us_external_port_export>),                       //           timer_1us_external_port.export
		.tristate_conduit_tcm_address_out                     (<connected-to-tristate_conduit_tcm_address_out>),                     //                  tristate_conduit.tcm_address_out
		.tristate_conduit_tcm_read_n_out                      (<connected-to-tristate_conduit_tcm_read_n_out>),                      //                                  .tcm_read_n_out
		.tristate_conduit_tcm_write_n_out                     (<connected-to-tristate_conduit_tcm_write_n_out>),                     //                                  .tcm_write_n_out
		.tristate_conduit_tcm_data_out                        (<connected-to-tristate_conduit_tcm_data_out>),                        //                                  .tcm_data_out
		.tristate_conduit_tcm_chipselect_n_out                (<connected-to-tristate_conduit_tcm_chipselect_n_out>),                //                                  .tcm_chipselect_n_out
		.tse_clk_clk                                          (<connected-to-tse_clk_clk>),                                          //                           tse_clk.clk
		.tse_led_crs                                          (<connected-to-tse_led_crs>),                                          //                           tse_led.crs
		.tse_led_link                                         (<connected-to-tse_led_link>),                                         //                                  .link
		.tse_led_panel_link                                   (<connected-to-tse_led_panel_link>),                                   //                                  .panel_link
		.tse_led_col                                          (<connected-to-tse_led_col>),                                          //                                  .col
		.tse_led_an                                           (<connected-to-tse_led_an>),                                           //                                  .an
		.tse_led_char_err                                     (<connected-to-tse_led_char_err>),                                     //                                  .char_err
		.tse_led_disp_err                                     (<connected-to-tse_led_disp_err>),                                     //                                  .disp_err
		.tse_mac_mac_misc_connection_xon_gen                  (<connected-to-tse_mac_mac_misc_connection_xon_gen>),                  //       tse_mac_mac_misc_connection.xon_gen
		.tse_mac_mac_misc_connection_xoff_gen                 (<connected-to-tse_mac_mac_misc_connection_xoff_gen>),                 //                                  .xoff_gen
		.tse_mac_mac_misc_connection_magic_wakeup             (<connected-to-tse_mac_mac_misc_connection_magic_wakeup>),             //                                  .magic_wakeup
		.tse_mac_mac_misc_connection_magic_sleep_n            (<connected-to-tse_mac_mac_misc_connection_magic_sleep_n>),            //                                  .magic_sleep_n
		.tse_mac_mac_misc_connection_ff_tx_crc_fwd            (<connected-to-tse_mac_mac_misc_connection_ff_tx_crc_fwd>),            //                                  .ff_tx_crc_fwd
		.tse_mac_mac_misc_connection_ff_tx_septy              (<connected-to-tse_mac_mac_misc_connection_ff_tx_septy>),              //                                  .ff_tx_septy
		.tse_mac_mac_misc_connection_tx_ff_uflow              (<connected-to-tse_mac_mac_misc_connection_tx_ff_uflow>),              //                                  .tx_ff_uflow
		.tse_mac_mac_misc_connection_ff_tx_a_full             (<connected-to-tse_mac_mac_misc_connection_ff_tx_a_full>),             //                                  .ff_tx_a_full
		.tse_mac_mac_misc_connection_ff_tx_a_empty            (<connected-to-tse_mac_mac_misc_connection_ff_tx_a_empty>),            //                                  .ff_tx_a_empty
		.tse_mac_mac_misc_connection_rx_err_stat              (<connected-to-tse_mac_mac_misc_connection_rx_err_stat>),              //                                  .rx_err_stat
		.tse_mac_mac_misc_connection_rx_frm_type              (<connected-to-tse_mac_mac_misc_connection_rx_frm_type>),              //                                  .rx_frm_type
		.tse_mac_mac_misc_connection_ff_rx_dsav               (<connected-to-tse_mac_mac_misc_connection_ff_rx_dsav>),               //                                  .ff_rx_dsav
		.tse_mac_mac_misc_connection_ff_rx_a_full             (<connected-to-tse_mac_mac_misc_connection_ff_rx_a_full>),             //                                  .ff_rx_a_full
		.tse_mac_mac_misc_connection_ff_rx_a_empty            (<connected-to-tse_mac_mac_misc_connection_ff_rx_a_empty>),            //                                  .ff_rx_a_empty
		.tse_mac_serdes_control_connection_export             (<connected-to-tse_mac_serdes_control_connection_export>),             // tse_mac_serdes_control_connection.export
		.tse_mdio_mdc                                         (<connected-to-tse_mdio_mdc>),                                         //                          tse_mdio.mdc
		.tse_mdio_mdio_in                                     (<connected-to-tse_mdio_mdio_in>),                                     //                                  .mdio_in
		.tse_mdio_mdio_out                                    (<connected-to-tse_mdio_mdio_out>),                                    //                                  .mdio_out
		.tse_mdio_mdio_oen                                    (<connected-to-tse_mdio_mdio_oen>),                                    //                                  .mdio_oen
		.tse_serial_txp                                       (<connected-to-tse_serial_txp>),                                       //                        tse_serial.txp
		.tse_serial_rxp                                       (<connected-to-tse_serial_rxp>),                                       //                                  .rxp
		.ctrl_io_lvds_export                                  (<connected-to-ctrl_io_lvds_export>)                                   //                      ctrl_io_lvds.export
	);

