/*
 * tran_registers.h
 *
 *  Created on: 06/10/2017
 *      Author: rfranca
 */

#ifndef TRAN_REGISTERS_H_
#define TRAN_REGISTERS_H_

	#define TRAN_TRANSPARENT_INTERFACE_REGISTERS_ADDRESS_OFFSET 0x20

	#define TRAN_INTERFACE_CONTROL_STATUS_REGISTER_ADDRESS      (0x00 + TRAN_TRANSPARENT_INTERFACE_REGISTERS_ADDRESS_OFFSET)
	#define TRAN_INTERFACE_ENABLE_CONTROL_BIT_MASK              (1 << 10)
	#define TRAN_INTERFACE_RX_ENABLE_CONTROL_BIT_MASK           (1 << 9)
	#define TRAN_INTERFACE_TX_ENABLE_CONTROL_BIT_MASK           (1 << 8)
	#define TRAN_INTERFACE_ERROR_INTERRUPT_ENABLE_BIT_MASK      (1 << 7)
	#define TRAN_DATA_RECEIVED_INTERRUPT_ENABLE_BIT_MASK        (1 << 6)
	#define TRAN_RX_FIFO_FULL_INTERRUPT_ENABLE_BIT_MASK         (1 << 5)
	#define TRAN_TX_FIFO_EMPTY_INTERRUPT_ENABLE_BIT_MASK        (1 << 4)
	#define TRAN_INTERFACE_ERROR_INTERRUPT_FLAG_MASK            (1 << 3)
	#define TRAN_DATA_RECEIVED_INTERRUPT_FLAG_MASK              (1 << 2)
	#define TRAN_RX_FIFO_FULL_INTERRUPT_FLAG_MASK               (1 << 1)
	#define TRAN_TX_FIFO_EMPTY_INTERRUPT_FLAG_MASK              (1 << 0)

	#define TRAN_RX_MODE_CONTROL_REGISTER_ADDRESS               (0x01 + TRAN_TRANSPARENT_INTERFACE_REGISTERS_ADDRESS_OFFSET)
	#define TRAN_RX_FIFO_USED_SPACE_VALUE_MASK                  (0b11111111 << 3)
	#define TRAN_RX_FIFO_RESET_CONTROL_BIT_MASK                 (1 << 2)
	#define TRAN_RX_FIFO_EMPTY_STATUS_BIT_MASK                  (1 << 1)
	#define TRAN_RX_FIFO_FULL_STATUS_BIT_MASK                   (1 << 0)

	#define TRAN_TX_MODE_CONTROL_REGISTER_ADDRESS               (0x02 + TRAN_TRANSPARENT_INTERFACE_REGISTERS_ADDRESS_OFFSET)
	#define TRAN_TX_FIFO_USED_SPACE_VALUE_MASK                  (0b11111111 << 3)
	#define TRAN_TX_FIFO_RESET_CONTROL_BIT_MASK                 (1 << 2)
	#define TRAN_TX_FIFO_EMPTY_STATUS_BIT_MASK                  (1 << 1)
	#define TRAN_TX_FIFO_FULL_STATUS_BIT_MASK                   (1 << 0)

#endif /* TRAN_REGISTERS_H_ */
